// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/v1/duckdb.proto

package duckdbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_v1_duckdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_duckdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_duckdb_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_v1_duckdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_duckdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_duckdb_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_v1_duckdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_duckdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_duckdb_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrowIpcChunk []byte                 `protobuf:"bytes,1,opt,name=arrow_ipc_chunk,json=arrowIpcChunk,proto3" json:"arrow_ipc_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_v1_duckdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_duckdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_duckdb_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetArrowIpcChunk() []byte {
	if x != nil {
		return x.ArrowIpcChunk
	}
	return nil
}

type QueryJsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJsonResponse) Reset() {
	*x = QueryJsonResponse{}
	mi := &file_proto_v1_duckdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJsonResponse) ProtoMessage() {}

func (x *QueryJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_duckdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJsonResponse.ProtoReflect.Descriptor instead.
func (*QueryJsonResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_duckdb_proto_rawDescGZIP(), []int{4}
}

func (x *QueryJsonResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_proto_v1_duckdb_proto protoreflect.FileDescriptor

const file_proto_v1_duckdb_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/duckdb.proto\x12\x0evldb.duckdb.v1\"C\n" +
	"\x0eExecuteRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\"E\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\"7\n" +
	"\rQueryResponse\x12&\n" +
	"\x0farrow_ipc_chunk\x18\x01 \x01(\fR\rarrowIpcChunk\"0\n" +
	"\x11QueryJsonResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData2\xfd\x01\n" +
	"\rDuckDbService\x12P\n" +
	"\rExecuteScript\x12\x1e.vldb.duckdb.v1.ExecuteRequest\x1a\x1f.vldb.duckdb.v1.ExecuteResponse\x12L\n" +
	"\vQueryStream\x12\x1c.vldb.duckdb.v1.QueryRequest\x1a\x1d.vldb.duckdb.v1.QueryResponse0\x01\x12L\n" +
	"\tQueryJson\x12\x1c.vldb.duckdb.v1.QueryRequest\x1a!.vldb.duckdb.v1.QueryJsonResponseB>Z<github.com/vldb/vldb-duckdb/demo/go-client/proto/v1;duckdbv1b\x06proto3"

var (
	file_proto_v1_duckdb_proto_rawDescOnce sync.Once
	file_proto_v1_duckdb_proto_rawDescData []byte
)

func file_proto_v1_duckdb_proto_rawDescGZIP() []byte {
	file_proto_v1_duckdb_proto_rawDescOnce.Do(func() {
		file_proto_v1_duckdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_duckdb_proto_rawDesc), len(file_proto_v1_duckdb_proto_rawDesc)))
	})
	return file_proto_v1_duckdb_proto_rawDescData
}

var file_proto_v1_duckdb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_duckdb_proto_goTypes = []any{
	(*ExecuteRequest)(nil),    // 0: vldb.duckdb.v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 1: vldb.duckdb.v1.ExecuteResponse
	(*QueryRequest)(nil),      // 2: vldb.duckdb.v1.QueryRequest
	(*QueryResponse)(nil),     // 3: vldb.duckdb.v1.QueryResponse
	(*QueryJsonResponse)(nil), // 4: vldb.duckdb.v1.QueryJsonResponse
}
var file_proto_v1_duckdb_proto_depIdxs = []int32{
	0, // 0: vldb.duckdb.v1.DuckDbService.ExecuteScript:input_type -> vldb.duckdb.v1.ExecuteRequest
	2, // 1: vldb.duckdb.v1.DuckDbService.QueryStream:input_type -> vldb.duckdb.v1.QueryRequest
	2, // 2: vldb.duckdb.v1.DuckDbService.QueryJson:input_type -> vldb.duckdb.v1.QueryRequest
	1, // 3: vldb.duckdb.v1.DuckDbService.ExecuteScript:output_type -> vldb.duckdb.v1.ExecuteResponse
	3, // 4: vldb.duckdb.v1.DuckDbService.QueryStream:output_type -> vldb.duckdb.v1.QueryResponse
	4, // 5: vldb.duckdb.v1.DuckDbService.QueryJson:output_type -> vldb.duckdb.v1.QueryJsonResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_duckdb_proto_init() }
func file_proto_v1_duckdb_proto_init() {
	if File_proto_v1_duckdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_duckdb_proto_rawDesc), len(file_proto_v1_duckdb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_duckdb_proto_goTypes,
		DependencyIndexes: file_proto_v1_duckdb_proto_depIdxs,
		MessageInfos:      file_proto_v1_duckdb_proto_msgTypes,
	}.Build()
	File_proto_v1_duckdb_proto = out.File
	file_proto_v1_duckdb_proto_goTypes = nil
	file_proto_v1_duckdb_proto_depIdxs = nil
}
