// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.31.1
// source: proto/v1/lancedb.proto

package lancedbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanceDbService_CreateTable_FullMethodName  = "/vldb.lancedb.v1.LanceDbService/CreateTable"
	LanceDbService_VectorUpsert_FullMethodName = "/vldb.lancedb.v1.LanceDbService/VectorUpsert"
	LanceDbService_VectorSearch_FullMethodName = "/vldb.lancedb.v1.LanceDbService/VectorSearch"
	LanceDbService_Delete_FullMethodName       = "/vldb.lancedb.v1.LanceDbService/Delete"
	LanceDbService_DropTable_FullMethodName    = "/vldb.lancedb.v1.LanceDbService/DropTable"
)

// LanceDbServiceClient is the client API for LanceDbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanceDbServiceClient interface {
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	VectorUpsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	VectorSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
}

type lanceDbServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanceDbServiceClient(cc grpc.ClientConnInterface) LanceDbServiceClient {
	return &lanceDbServiceClient{cc}
}

func (c *lanceDbServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, LanceDbService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceDbServiceClient) VectorUpsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, LanceDbService_VectorUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceDbServiceClient) VectorSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, LanceDbService_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceDbServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, LanceDbService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lanceDbServiceClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, LanceDbService_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanceDbServiceServer is the server API for LanceDbService service.
// All implementations must embed UnimplementedLanceDbServiceServer
// for forward compatibility.
type LanceDbServiceServer interface {
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	VectorUpsert(context.Context, *UpsertRequest) (*UpsertResponse, error)
	VectorSearch(context.Context, *SearchRequest) (*SearchResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	mustEmbedUnimplementedLanceDbServiceServer()
}

// UnimplementedLanceDbServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanceDbServiceServer struct{}

func (UnimplementedLanceDbServiceServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedLanceDbServiceServer) VectorUpsert(context.Context, *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorUpsert not implemented")
}
func (UnimplementedLanceDbServiceServer) VectorSearch(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedLanceDbServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLanceDbServiceServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedLanceDbServiceServer) mustEmbedUnimplementedLanceDbServiceServer() {}
func (UnimplementedLanceDbServiceServer) testEmbeddedByValue()                        {}

// UnsafeLanceDbServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanceDbServiceServer will
// result in compilation errors.
type UnsafeLanceDbServiceServer interface {
	mustEmbedUnimplementedLanceDbServiceServer()
}

func RegisterLanceDbServiceServer(s grpc.ServiceRegistrar, srv LanceDbServiceServer) {
	// If the following call panics, it indicates UnimplementedLanceDbServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanceDbService_ServiceDesc, srv)
}

func _LanceDbService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceDbServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceDbService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceDbServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceDbService_VectorUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceDbServiceServer).VectorUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceDbService_VectorUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceDbServiceServer).VectorUpsert(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceDbService_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceDbServiceServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceDbService_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceDbServiceServer).VectorSearch(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceDbService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceDbServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceDbService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceDbServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LanceDbService_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceDbServiceServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceDbService_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceDbServiceServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LanceDbService_ServiceDesc is the grpc.ServiceDesc for LanceDbService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanceDbService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vldb.lancedb.v1.LanceDbService",
	HandlerType: (*LanceDbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _LanceDbService_CreateTable_Handler,
		},
		{
			MethodName: "VectorUpsert",
			Handler:    _LanceDbService_VectorUpsert_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _LanceDbService_VectorSearch_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LanceDbService_Delete_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _LanceDbService_DropTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/lancedb.proto",
}
