// schema.go bootstraps the shared PostgreSQL combined-store schema so both dialect flavors can reuse one durable table layout.
// schema.go 用于初始化 PostgreSQL 组合库共享 schema，让两种方言都能复用同一套长期表结构。
package vldb_postgres

import (
	"context"
	"fmt"
	"strings"
	"time"
)

// ensureSchema creates the shared PostgreSQL tables, common indexes, dialect-specific lexical indexes, and deterministic debug seeds used by the combined runtime.
// ensureSchema 用于创建组合运行时共享的 PostgreSQL 表、公共索引、方言化 lexical 索引以及确定性的调试种子数据。
func (s *Store) ensureSchema(ctx context.Context) error {
	if s == nil || s.pool == nil {
		return fmt.Errorf("postgres store is not initialized")
	}
	callCtx, cancel := s.bootstrapContext(ctx)
	defer cancel()

	// Bootstrap the version table before the rest of the schema so incompatible tracked versions fail fast before later DDL mutates more objects.
	// 先初始化版本表，再继续其余 schema，这样版本不兼容时可以在后续 DDL 改动更多对象前快速失败。
	if err := s.ensureSchemaVersionTable(callCtx); err != nil {
		return err
	}
	if err := s.validateTrackedSchemaVersions(callCtx); err != nil {
		return err
	}

	// Create the shared core tables only after the tracked version contract is acceptable for this runtime.
	// 仅在当前运行时可接受版本契约后，继续创建共享核心表。
	statements := []string{
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	scope TEXT NOT NULL,
	language TEXT NOT NULL,
	category_name TEXT NOT NULL,
	phrase TEXT NOT NULL,
	model TEXT NOT NULL,
	dimension INTEGER NOT NULL,
	rules_hash TEXT NOT NULL,
	embedding VECTOR(%d) NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (scope, language, category_name, phrase, model, dimension, rules_hash)
)`, s.noiseEmbeddingsTable(), s.cfg.EmbeddingDimension),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	profile TEXT NOT NULL DEFAULT '',
	delete_confirm_code TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.usersTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.teamsTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	name TEXT NOT NULL,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(team_id, name)
)`, s.spacesTable(), s.teamsTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	name TEXT NOT NULL,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(space_id, name)
)`, s.projectsTable(), s.teamsTable(), s.spacesTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_key TEXT NOT NULL,
	user_id BIGINT NOT NULL REFERENCES %s(id),
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	turn_count INTEGER NOT NULL DEFAULT 0,
	last_summarized_id BIGINT NOT NULL DEFAULT 0,
	last_compacted_turn_id BIGINT NOT NULL DEFAULT 0,
	summarize_content TEXT NOT NULL DEFAULT '',
	summarize_budget INTEGER NOT NULL DEFAULT 0,
	last_extract_observed_at TIMESTAMPTZ NULL,
	last_extract_completed_at TIMESTAMPTZ NULL,
	last_compacted_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(project_id, session_key)
)`, s.sessionsTable(), s.usersTable(), s.teamsTable(), s.spacesTable(), s.projectsTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	dehydrated_content TEXT NOT NULL,
	dehydrated_budget INTEGER NOT NULL DEFAULT 0,
	extracted_status SMALLINT NOT NULL DEFAULT 0,
	details TEXT NOT NULL DEFAULT '',
	details_budget INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.turnsTable(), s.sessionsTable(), s.projectsTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	user_id BIGINT NOT NULL REFERENCES %s(id),
	origin_session_id BIGINT NOT NULL DEFAULT 0,
	source_turn_id BIGINT NULL,
	vector_id TEXT NOT NULL UNIQUE,
	embedding VECTOR(%d) NOT NULL,
	source_kind INTEGER NOT NULL DEFAULT 0,
	scope_level INTEGER NOT NULL DEFAULT 1,
	category INTEGER NOT NULL,
	abstract TEXT NOT NULL,
	details TEXT NOT NULL,
	memory_status INTEGER NOT NULL DEFAULT 0,
	priority INTEGER NOT NULL DEFAULT 2,
	memory_level INTEGER NOT NULL DEFAULT 2,
	refresh_weight INTEGER NOT NULL DEFAULT 0,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	status_reason TEXT NOT NULL DEFAULT '',
	expires_at TIMESTAMPTZ NULL,
	last_recalled_at TIMESTAMPTZ NULL,
	last_adopted_at TIMESTAMPTZ NULL,
	last_reinforced_at TIMESTAMPTZ NULL,
	recalled_count INTEGER NOT NULL DEFAULT 0,
	adopted_count INTEGER NOT NULL DEFAULT 0,
	reinforcement_count INTEGER NOT NULL DEFAULT 0,
	cross_session_adopted_count INTEGER NOT NULL DEFAULT 0,
	decay_disabled BOOLEAN NOT NULL DEFAULT FALSE,
	dedupe_hash TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.memoryNodesTable(), s.teamsTable(), s.spacesTable(), s.projectsTable(), s.usersTable(), s.cfg.EmbeddingDimension),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	memory_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
	context_key TEXT NOT NULL,
	context_value TEXT NOT NULL,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	last_supported_at TIMESTAMPTZ NULL,
	last_rebutted_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (memory_id, context_key, context_value)
)`, s.memoryContextEdgesTable(), s.memoryNodesTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	turn_id BIGINT NULL,
	profile_type SMALLINT NOT NULL,
	bind_id BIGINT NOT NULL,
	content TEXT NOT NULL,
	profile_status SMALLINT NOT NULL DEFAULT 1,
	priority SMALLINT NOT NULL DEFAULT 2,
	profile_level SMALLINT NOT NULL DEFAULT 0,
	level_reason TEXT NOT NULL DEFAULT '',
	refresh_weight INTEGER NOT NULL DEFAULT 0,
	source_kind SMALLINT NOT NULL DEFAULT 0,
	source_id BIGINT NOT NULL DEFAULT 0,
	status_reason TEXT NOT NULL DEFAULT '',
	expires_at TIMESTAMPTZ NULL,
	superseded_by_id BIGINT NOT NULL DEFAULT 0,
	profile_date TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.profileNodesTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	profile_type SMALLINT NOT NULL,
	bind_id BIGINT NOT NULL,
	instruction TEXT NOT NULL,
	instruction_status SMALLINT NOT NULL DEFAULT 0,
	review_result_json TEXT NOT NULL DEFAULT '',
	failure_reason TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.profileInstructionsTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recycle_type TEXT NOT NULL,
	session_id BIGINT NOT NULL DEFAULT 0,
	project_id BIGINT NOT NULL DEFAULT 0,
	reason TEXT NOT NULL DEFAULT '',
	recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	purged_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, s.recycleBatchesTable()),
		fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	batch_id BIGINT NOT NULL DEFAULT 0,
	vector_id TEXT NOT NULL,
	job_type TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0,
	next_run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	claimed_at TIMESTAMPTZ NULL,
	completed_at TIMESTAMPTZ NULL,
	last_error TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(vector_id, job_type, batch_id)
)`, s.vectorGCJobsTable()),
	}
	for _, statement := range statements {
		if _, err := s.pool.Exec(callCtx, strings.TrimSpace(statement)); err != nil {
			return fmt.Errorf("bootstrap postgres schema object: %w", err)
		}
	}
	if err := s.ensureCommonIndexes(callCtx); err != nil {
		return err
	}
	if err := s.ensureDebugSeedWorkspace(callCtx); err != nil {
		return err
	}
	if err := s.syncDebugSeedSequences(callCtx); err != nil {
		return err
	}
	if err := s.ensureVectorIndex(callCtx); err != nil {
		return err
	}
	if err := s.dialect.EnsureSearchIndexes(callCtx, s); err != nil {
		return err
	}
	return s.backfillTrackedSchemaVersions(callCtx)
}

// ensureCommonIndexes creates the shared non-lexical indexes reused by both PostgreSQL dialect flavors.
// ensureCommonIndexes 用于创建两种 PostgreSQL 方言都会复用的非 lexical 公共索引。
func (s *Store) ensureCommonIndexes(ctx context.Context) error {
	statements := []string{
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_noise_embeddings_lookup ON %s (scope, language, model, dimension, rules_hash, category_name, phrase)`, s.noiseEmbeddingsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_scope ON %s (user_id, team_id, space_id, project_id, updated_at DESC)`, s.sessionsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_project_session ON %s (project_id, session_key)`, s.sessionsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_compact_boundary ON %s (project_id, last_compacted_turn_id, id)`, s.sessionsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_session ON %s (session_id, id)`, s.turnsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_project_status ON %s (project_id, extracted_status, id)`, s.turnsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_project_active_window ON %s (project_id, memory_status, expires_at, id)`, s.memoryNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_source_turn ON %s (source_turn_id, id)`, s.memoryNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_origin_session_active ON %s (origin_session_id, memory_status, expires_at, id)`, s.memoryNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_dedupe_window ON %s (origin_session_id, project_id, user_id, source_kind, scope_level, dedupe_hash, memory_status, expires_at, created_at DESC)`, s.memoryNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_lookup ON %s (context_key, context_value, memory_id)`, s.memoryContextEdgesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_memory ON %s (memory_id)`, s.memoryContextEdgesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_bind_status ON %s (profile_type, bind_id, profile_status, id)`, s.profileNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_active_window ON %s (profile_type, bind_id, profile_status, expires_at, id)`, s.profileNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_turn ON %s (turn_id, id)`, s.profileNodesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_instructions_target ON %s (profile_type, bind_id, id)`, s.profileInstructionsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_batches_lookup ON %s (recycle_type, recycled_at, id)`, s.recycleBatchesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_batches_session ON %s (session_id, project_id, id)`, s.recycleBatchesTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_vector_gc_jobs_pending ON %s (completed_at, next_run_at, id)`, s.vectorGCJobsTable()),
		fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_vector_gc_jobs_batch ON %s (batch_id, id)`, s.vectorGCJobsTable()),
	}
	for _, statement := range statements {
		if _, err := s.pool.Exec(ctx, statement); err != nil {
			return fmt.Errorf("create postgres common index: %w", err)
		}
	}
	return nil
}

// ensureVectorIndex creates the shared pgvector ANN index used by both flavors for first-stage semantic recall.
// ensureVectorIndex 用于创建两种方言共享的 pgvector ANN 索引，服务首阶段语义召回。
func (s *Store) ensureVectorIndex(ctx context.Context) error {
	statement := fmt.Sprintf(`
CREATE INDEX IF NOT EXISTS %s ON %s USING ivfflat (embedding vector_cosine_ops) WITH (lists = %d)
`, quoteIdentifier("idx_vmm_memory_nodes_embedding_ivfflat"), s.memoryNodesTable(), s.cfg.VectorLists)
	if _, err := s.pool.Exec(ctx, strings.TrimSpace(statement)); err != nil {
		return fmt.Errorf("create postgres vector index: %w", err)
	}
	return nil
}

// ensureDebugSeedWorkspace inserts the deterministic default user/team/space/project rows expected by local debugging flows.
// ensureDebugSeedWorkspace 用于插入本地调试流期望的确定性默认 user/team/space/project 行。
func (s *Store) ensureDebugSeedWorkspace(ctx context.Context) error {
	if s == nil || s.pool == nil {
		return fmt.Errorf("postgres store is not initialized")
	}
	var projectCount int
	countSQL := fmt.Sprintf(`SELECT COUNT(*) FROM %s`, s.projectsTable())
	if err := s.pool.QueryRow(ctx, countSQL).Scan(&projectCount); err != nil {
		return fmt.Errorf("count postgres projects before debug seed bootstrap: %w", err)
	}
	if !shouldSeedDebugWorkspace(projectCount) {
		return nil
	}
	now := time.Now().UTC()
	if _, err := s.upsertDebugSeedUser(ctx, s.pool, debugSeedDefaultName, now); err != nil {
		return err
	}
	teamID, err := s.upsertDebugSeedTeam(ctx, s.pool, debugSeedDefaultName, now)
	if err != nil {
		return err
	}
	spaceID, err := s.upsertDebugSeedSpace(ctx, s.pool, teamID, debugSeedDefaultName, now)
	if err != nil {
		return err
	}
	if _, err := s.upsertDebugSeedProject(ctx, s.pool, teamID, spaceID, debugSeedDefaultName, now); err != nil {
		return err
	}
	return nil
}

// shouldSeedDebugWorkspace reports whether startup should inject the deterministic default hierarchy, matching SQLite by seeding only truly empty workspaces.
// shouldSeedDebugWorkspace 用于判断启动时是否应注入确定性的默认层级；其语义与 SQLite 保持一致，只在工作区真正为空时补种。
func shouldSeedDebugWorkspace(projectCount int) bool {
	return projectCount == 0
}

// upsertDebugSeedUser resolves or creates the default debug user by name so empty workspaces with restored ids can still bootstrap safely.
// upsertDebugSeedUser 用于按名称解析或创建默认调试用户，确保即使空工作区里的 id 已被恢复过，启动也能安全补种。
func (s *Store) upsertDebugSeedUser(ctx context.Context, q profileQueryer, userName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (name, profile, delete_confirm_code, created_at, updated_at)
VALUES ($1, '', '', $2, $2)
ON CONFLICT (name)
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`, s.usersTable())
	var userID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), strings.TrimSpace(userName), now.UTC()).Scan(&userID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed user: %w", err)
	}
	return userID, nil
}

// upsertDebugSeedTeam resolves or creates the default debug team by its stable business key so startup does not depend on one hard-coded row id.
// upsertDebugSeedTeam 用于按稳定的业务键解析或创建默认调试 team，避免启动逻辑依赖单个硬编码行 id。
func (s *Store) upsertDebugSeedTeam(ctx context.Context, q profileQueryer, teamName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (name, profile, created_at, updated_at)
VALUES ($1, '', $2, $2)
ON CONFLICT (name)
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`, s.teamsTable())
	var teamID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), strings.TrimSpace(teamName), now.UTC()).Scan(&teamID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed team: %w", err)
	}
	return teamID, nil
}

// upsertDebugSeedSpace resolves or creates the default debug space under the resolved team so restored name collisions cannot break empty-workspace bootstrap.
// upsertDebugSeedSpace 用于在已解析 team 下解析或创建默认调试 space，避免恢复数据后的同名冲突打断空工作区补种。
func (s *Store) upsertDebugSeedSpace(ctx context.Context, q profileQueryer, teamID uint64, spaceName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (team_id, name, profile, created_at, updated_at)
VALUES ($1, $2, '', $3, $3)
ON CONFLICT (team_id, name)
DO UPDATE SET team_id = EXCLUDED.team_id
RETURNING id
`, s.spacesTable())
	var spaceID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), int64(teamID), strings.TrimSpace(spaceName), now.UTC()).Scan(&spaceID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed space: %w", err)
	}
	return spaceID, nil
}

// upsertDebugSeedProject resolves or creates the default debug project under the resolved Team/Space path so startup keeps one stable default hierarchy by name.
// upsertDebugSeedProject 用于在已解析的 Team/Space 路径下解析或创建默认调试项目，保证启动时按名称维持一条稳定的默认层级。
func (s *Store) upsertDebugSeedProject(ctx context.Context, q profileQueryer, teamID, spaceID uint64, projectName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (team_id, space_id, name, profile, created_at, updated_at)
VALUES ($1, $2, $3, '', $4, $4)
ON CONFLICT (space_id, name)
DO UPDATE SET team_id = EXCLUDED.team_id, space_id = EXCLUDED.space_id
RETURNING id
`, s.projectsTable())
	var projectID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), int64(teamID), int64(spaceID), strings.TrimSpace(projectName), now.UTC()).Scan(&projectID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed project: %w", err)
	}
	return projectID, nil
}

// syncDebugSeedSequences advances identity sequences after debug-seed upserts so later auto-generated ids stay aligned with the current table maxima.
// syncDebugSeedSequences 用于在调试种子 upsert 完成后推进 identity sequence，确保后续自动 id 与当前表内最大值保持对齐。
func (s *Store) syncDebugSeedSequences(ctx context.Context) error {
	for _, tableName := range []string{"vmm_users", "vmm_teams", "vmm_spaces", "vmm_projects", "vmm_sessions", "vmm_turn_records", "vmm_memory_nodes", "vmm_profile_nodes", "vmm_profile_instructions"} {
		if err := s.syncIdentitySequence(ctx, tableName); err != nil {
			return err
		}
	}
	return nil
}

// syncIdentitySequence aligns one table identity sequence with the current MAX(id) so manual seed rows and later auto ids can coexist safely.
// syncIdentitySequence 用于让某张表的 identity sequence 与当前 MAX(id) 对齐，确保手工种子行和后续自动 id 能安全共存。
func (s *Store) syncIdentitySequence(ctx context.Context, tableName string) error {
	statement := fmt.Sprintf(`
SELECT setval(
	pg_get_serial_sequence($1, 'id'),
	GREATEST(COALESCE((SELECT MAX(id) FROM %s), 1), 1),
	true
)
`, s.qualifiedTable(tableName))
	if _, err := s.pool.Exec(ctx, strings.TrimSpace(statement), s.qualifiedTable(tableName)); err != nil {
		return fmt.Errorf("sync postgres identity sequence for %s: %w", tableName, err)
	}
	return nil
}
