// schema.go bootstraps the shared PostgreSQL combined-store schema so both dialect flavors can reuse one durable table layout.
// schema.go 用于初始化 PostgreSQL 组合库共享 schema，让两种方言都能复用同一套长期表结构。
package vldb_postgres

import (
	"context"
	"fmt"
	"strings"
	"time"

	logicdomain "github.com/openvulcan/vmm/internal/logic/domain"
)

// ensureSchema creates the shared PostgreSQL tables, common indexes, dialect-specific lexical indexes, and deterministic debug seeds used by the combined runtime.
// ensureSchema 用于创建组合运行时共享的 PostgreSQL 表、公共索引、方言化 lexical 索引以及确定性的调试种子数据。
func (r *maintenanceRepository) ensureSchema(ctx context.Context) error {
	if r == nil || r.shared == nil || r.shared.pool == nil {
		return fmt.Errorf("postgres store is not initialized")
	}
	callCtx, cancel := r.maintenanceBootstrapContext(ctx)
	defer cancel()

	// Bootstrap the version table before the rest of the schema so incompatible tracked versions fail fast before later DDL mutates more objects.
	// 先初始化版本表，再继续其余 schema，这样版本不兼容时可以在后续 DDL 改动更多对象前快速失败。
	if err := r.ensureSchemaVersionTable(callCtx); err != nil {
		return err
	}
	if err := r.validateTrackedSchemaVersions(callCtx); err != nil {
		return err
	}
	if err := r.applyTrackedSchemaMigrations(callCtx); err != nil {
		return err
	}

	// Create the shared core tables only after the tracked version contract is acceptable and any older tracked versions have already been migrated forward.
	// 仅在当前运行时可接受版本契约、且旧版本已完成前向迁移后，继续创建共享核心表。
	statements := []postgresDDLStatement{
		{name: "vmm_noise_embeddings", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	scope TEXT NOT NULL,
	language TEXT NOT NULL,
	category_name TEXT NOT NULL,
	phrase TEXT NOT NULL,
	model TEXT NOT NULL,
	dimension INTEGER NOT NULL,
	rules_hash TEXT NOT NULL,
	embedding VECTOR(%d) NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (scope, language, category_name, phrase, model, dimension, rules_hash)
)`, r.noiseEmbeddingsTable(), r.shared.cfg.EmbeddingDimension)},
		{name: "vmm_users", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	profile TEXT NOT NULL DEFAULT '',
	delete_confirm_code TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.usersTable())},
		{name: "vmm_teams", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.teamsTable())},
		{name: "vmm_spaces", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	name TEXT NOT NULL,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(team_id, name)
)`, r.spacesTable(), r.teamsTable())},
		{name: "vmm_projects", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	name TEXT NOT NULL,
	profile TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(space_id, name)
)`, r.projectsTable(), r.teamsTable(), r.spacesTable())},
		{name: "vmm_sessions", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_key TEXT NOT NULL,
	user_id BIGINT NOT NULL REFERENCES %s(id),
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	turn_count INTEGER NOT NULL DEFAULT 0,
	last_summarized_id BIGINT NOT NULL DEFAULT 0,
	last_compacted_turn_id BIGINT NOT NULL DEFAULT 0,
	summarize_content TEXT NOT NULL DEFAULT '',
	summarize_budget INTEGER NOT NULL DEFAULT 0,
	last_extract_observed_at TIMESTAMPTZ NULL,
	last_extract_completed_at TIMESTAMPTZ NULL,
	last_compacted_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(project_id, session_key)
)`, r.sessionsTable(), r.usersTable(), r.teamsTable(), r.spacesTable(), r.projectsTable())},
		{name: "vmm_turn_records", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	dehydrated_content TEXT NOT NULL,
	dehydrated_budget INTEGER NOT NULL DEFAULT 0,
	extracted_status SMALLINT NOT NULL DEFAULT 0,
	details TEXT NOT NULL DEFAULT '',
	details_budget INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.turnsTable(), r.sessionsTable(), r.projectsTable())},
	}
	statements = append(statements, postgresTurnAnalysisFailureSchemaStatements(r)...)
	statements = append(statements, []postgresDDLStatement{
		{name: "vmm_memory_nodes", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id BIGINT NOT NULL REFERENCES %s(id),
	space_id BIGINT NOT NULL REFERENCES %s(id),
	project_id BIGINT NOT NULL REFERENCES %s(id),
	user_id BIGINT NOT NULL REFERENCES %s(id),
	origin_session_id BIGINT NOT NULL DEFAULT 0,
	source_turn_id BIGINT NULL,
	vector_id TEXT NOT NULL UNIQUE,
	embedding VECTOR(%d) NOT NULL,
	source_kind INTEGER NOT NULL DEFAULT 0,
	scope_level INTEGER NOT NULL DEFAULT 1,
	category INTEGER NOT NULL,
	abstract TEXT NOT NULL,
	details TEXT NOT NULL,
	memory_status INTEGER NOT NULL DEFAULT 0,
	priority INTEGER NOT NULL DEFAULT 2,
	memory_level INTEGER NOT NULL DEFAULT 2,
	refresh_weight INTEGER NOT NULL DEFAULT 0,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	status_reason TEXT NOT NULL DEFAULT '',
	expires_at TIMESTAMPTZ NULL,
	last_recalled_at TIMESTAMPTZ NULL,
	last_adopted_at TIMESTAMPTZ NULL,
	last_reinforced_at TIMESTAMPTZ NULL,
	recalled_count INTEGER NOT NULL DEFAULT 0,
	adopted_count INTEGER NOT NULL DEFAULT 0,
	reinforcement_count INTEGER NOT NULL DEFAULT 0,
	cross_session_adopted_count INTEGER NOT NULL DEFAULT 0,
	decay_disabled BOOLEAN NOT NULL DEFAULT FALSE,
	dedupe_hash TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.memoryNodesTable(), r.teamsTable(), r.spacesTable(), r.projectsTable(), r.usersTable(), r.shared.cfg.EmbeddingDimension)},
		{name: "vmm_memory_context_edges", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	memory_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
	context_key TEXT NOT NULL,
	context_value TEXT NOT NULL,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	last_supported_at TIMESTAMPTZ NULL,
	last_rebutted_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (memory_id, context_key, context_value)
)`, r.memoryContextEdgesTable(), r.memoryNodesTable())},
		{name: "vmm_profile_nodes", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	turn_id BIGINT NULL,
	profile_type SMALLINT NOT NULL,
	bind_id BIGINT NOT NULL,
	content TEXT NOT NULL,
	profile_status SMALLINT NOT NULL DEFAULT 1,
	priority SMALLINT NOT NULL DEFAULT 2,
	profile_level SMALLINT NOT NULL DEFAULT 0,
	level_reason TEXT NOT NULL DEFAULT '',
	refresh_weight INTEGER NOT NULL DEFAULT 0,
	source_kind SMALLINT NOT NULL DEFAULT 0,
	source_id BIGINT NOT NULL DEFAULT 0,
	status_reason TEXT NOT NULL DEFAULT '',
	expires_at TIMESTAMPTZ NULL,
	superseded_by_id BIGINT NOT NULL DEFAULT 0,
	profile_date TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.profileNodesTable())},
		{name: "vmm_profile_instructions", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	profile_type SMALLINT NOT NULL,
	bind_id BIGINT NOT NULL,
	instruction TEXT NOT NULL,
	instruction_status SMALLINT NOT NULL DEFAULT 0,
	review_result_json TEXT NOT NULL DEFAULT '',
	failure_reason TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.profileInstructionsTable())},
		{name: "vmm_recycle_batches", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	recycle_type TEXT NOT NULL,
	session_id BIGINT NOT NULL DEFAULT 0,
	project_id BIGINT NOT NULL DEFAULT 0,
	reason TEXT NOT NULL DEFAULT '',
	recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	purged_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.recycleBatchesTable())},
		{name: "vmm_recycle_jobs", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id BIGINT NOT NULL DEFAULT 0,
	project_id BIGINT NOT NULL DEFAULT 0,
	job_type TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0,
	next_run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	claimed_at TIMESTAMPTZ NULL,
	last_error TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(session_id, job_type)
)`, r.recycleJobsTable())},
		{name: "vmm_memory_nodes_trash", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	batch_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
	recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	recycle_reason TEXT NOT NULL DEFAULT '',
	id BIGINT NOT NULL,
	team_id BIGINT NOT NULL,
	space_id BIGINT NOT NULL,
	project_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	origin_session_id BIGINT NOT NULL DEFAULT 0,
	source_turn_id BIGINT NULL,
	vector_id TEXT NOT NULL,
	embedding VECTOR(%d) NOT NULL,
	source_kind INTEGER NOT NULL DEFAULT 0,
	scope_level INTEGER NOT NULL DEFAULT 1,
	category INTEGER NOT NULL,
	abstract TEXT NOT NULL,
	details TEXT NOT NULL,
	memory_status INTEGER NOT NULL DEFAULT 0,
	priority INTEGER NOT NULL DEFAULT 2,
	memory_level INTEGER NOT NULL DEFAULT 2,
	refresh_weight INTEGER NOT NULL DEFAULT 0,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	status_reason TEXT NOT NULL DEFAULT '',
	expires_at TIMESTAMPTZ NULL,
	last_recalled_at TIMESTAMPTZ NULL,
	last_adopted_at TIMESTAMPTZ NULL,
	last_reinforced_at TIMESTAMPTZ NULL,
	recalled_count INTEGER NOT NULL DEFAULT 0,
	adopted_count INTEGER NOT NULL DEFAULT 0,
	reinforcement_count INTEGER NOT NULL DEFAULT 0,
	cross_session_adopted_count INTEGER NOT NULL DEFAULT 0,
	decay_disabled BOOLEAN NOT NULL DEFAULT FALSE,
	dedupe_hash TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (batch_id, id)
)`, r.memoryNodesTrashTable(), r.recycleBatchesTable(), r.shared.cfg.EmbeddingDimension)},
		{name: "vmm_memory_context_edges_trash", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	batch_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
	recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	recycle_reason TEXT NOT NULL DEFAULT '',
	memory_id BIGINT NOT NULL,
	context_key TEXT NOT NULL,
	context_value TEXT NOT NULL,
	support_count INTEGER NOT NULL DEFAULT 0,
	rebuttal_count INTEGER NOT NULL DEFAULT 0,
	last_supported_at TIMESTAMPTZ NULL,
	last_rebutted_at TIMESTAMPTZ NULL,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (batch_id, memory_id, context_key, context_value)
)`, r.memoryContextEdgesTrashTable(), r.recycleBatchesTable())},
		{name: "vmm_turn_records_trash", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	batch_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
	recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	recycle_reason TEXT NOT NULL DEFAULT '',
	id BIGINT NOT NULL,
	session_id BIGINT NOT NULL,
	project_id BIGINT NOT NULL,
	dehydrated_content TEXT NOT NULL,
	dehydrated_budget INTEGER NOT NULL DEFAULT 0,
	extracted_status SMALLINT NOT NULL DEFAULT 0,
	details TEXT NOT NULL DEFAULT '',
	details_budget INTEGER NOT NULL DEFAULT 0,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	PRIMARY KEY (batch_id, id)
)`, r.turnsTrashTable(), r.recycleBatchesTable())},
		{name: "vmm_vector_gc_jobs", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	batch_id BIGINT NOT NULL DEFAULT 0,
	vector_id TEXT NOT NULL,
	job_type TEXT NOT NULL,
	attempt_count INTEGER NOT NULL DEFAULT 0,
	next_run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	claimed_at TIMESTAMPTZ NULL,
	completed_at TIMESTAMPTZ NULL,
	last_error TEXT NOT NULL DEFAULT '',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	UNIQUE(vector_id, job_type, batch_id)
)`, r.vectorGCJobsTable())},
	}...)
	statements = append(statements, postgresManagementSchemaStatements(r)...)
	for _, statement := range statements {
		if _, err := r.shared.pool.Exec(callCtx, strings.TrimSpace(statement.sql)); err != nil {
			return postgresSchemaObjectBootstrapError(statement, err)
		}
	}
	if err := r.ensureCommonIndexes(callCtx); err != nil {
		return err
	}
	if err := r.ensureDebugSeedWorkspace(callCtx); err != nil {
		return err
	}
	if err := r.syncDebugSeedSequences(callCtx); err != nil {
		return err
	}
	if err := r.ensureVectorIndex(callCtx); err != nil {
		return err
	}
	if err := r.shared.dialect.EnsureSearchIndexes(callCtx, r); err != nil {
		return err
	}
	return r.backfillTrackedSchemaVersions(callCtx)
}

// postgresTurnAnalysisFailureSchemaStatements returns the durable per-turn retry table used by fresh bootstrap and upgrades.
// postgresTurnAnalysisFailureSchemaStatements 用于返回全新初始化与升级共同使用的逐 turn 持久化重试表。
func postgresTurnAnalysisFailureSchemaStatements(r *maintenanceRepository) []postgresDDLStatement {
	return []postgresDDLStatement{
		{name: "vmm_turn_analysis_failures", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  turn_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
  session_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  terminal_status TEXT NOT NULL DEFAULT 'retrying',
  last_error TEXT NOT NULL DEFAULT '',
  last_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (turn_id, stage)
)`, r.maintenanceQualifiedTable("vmm_turn_analysis_failures"), r.turnsTable(), r.sessionsTable())},
		{name: "idx_vmm_turn_analysis_failures_session", sql: fmt.Sprintf(`
CREATE INDEX IF NOT EXISTS idx_vmm_turn_analysis_failures_session
ON %s(session_id, terminal_status, turn_id)
`, r.maintenanceQualifiedTable("vmm_turn_analysis_failures"))},
	}
}

// postgresManagementSchemaStatements returns the shared management schema used by fresh bootstrap and upgrades.
// postgresManagementSchemaStatements 用于返回全新初始化与升级共同使用的管理 schema。
func postgresManagementSchemaStatements(r *maintenanceRepository) []postgresDDLStatement {
	return []postgresDDLStatement{
		{name: "vmm_management_session_states", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  session_id BIGINT PRIMARY KEY,
  status TEXT NOT NULL DEFAULT 'active',
  revision BIGINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`, r.maintenanceQualifiedTable("vmm_management_session_states"))},
		{name: "vmm_management_previews", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  preview_token TEXT PRIMARY KEY,
  target_type TEXT NOT NULL,
  target_ids_json TEXT NOT NULL,
  action TEXT NOT NULL,
  source TEXT NOT NULL,
  impact_json TEXT NOT NULL,
  impact_revision TEXT NOT NULL,
  confirm_text TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  consumed_at TIMESTAMPTZ NULL
)`, r.maintenanceQualifiedTable("vmm_management_previews"))},
		{name: "vmm_management_operations", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  operation_id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_ids_json TEXT NOT NULL,
  status TEXT NOT NULL,
  batch_id BIGINT NOT NULL DEFAULT 0,
  error_code TEXT NOT NULL DEFAULT '',
  error_message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ NULL
)`, r.maintenanceQualifiedTable("vmm_management_operations"))},
		{name: "vmm_management_recycle_batches", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  batch_id BIGINT PRIMARY KEY REFERENCES %s(id) ON DELETE CASCADE,
  source TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_ids_json TEXT NOT NULL,
  restorable BOOLEAN NOT NULL DEFAULT FALSE,
  state TEXT NOT NULL,
  expires_at TIMESTAMPTZ NULL,
  restored_at TIMESTAMPTZ NULL,
  operation_id TEXT NOT NULL DEFAULT ''
)`, r.maintenanceQualifiedTable("vmm_management_recycle_batches"), r.recycleBatchesTable())},
		{name: "vmm_sessions_trash", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  batch_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
  recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  recycle_reason TEXT NOT NULL DEFAULT '',
  id BIGINT NOT NULL,
  session_key TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL,
  project_id BIGINT NOT NULL,
  turn_count INTEGER NOT NULL DEFAULT 0,
  last_summarized_id BIGINT NOT NULL DEFAULT 0,
  last_compacted_turn_id BIGINT NOT NULL DEFAULT 0,
  summarize_content TEXT NOT NULL DEFAULT '',
  summarize_budget INTEGER NOT NULL DEFAULT 0,
  last_extract_observed_at TIMESTAMPTZ NULL,
  last_extract_completed_at TIMESTAMPTZ NULL,
  last_compacted_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, id)
)`, r.maintenanceQualifiedTable("vmm_sessions_trash"), r.recycleBatchesTable())},
		{name: "vmm_profile_nodes_trash", sql: fmt.Sprintf(`
CREATE TABLE IF NOT EXISTS %s (
  batch_id BIGINT NOT NULL REFERENCES %s(id) ON DELETE CASCADE,
  recycled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  recycle_reason TEXT NOT NULL DEFAULT '',
  id BIGINT NOT NULL,
  turn_id BIGINT NULL,
  profile_type SMALLINT NOT NULL,
  bind_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  profile_status SMALLINT NOT NULL DEFAULT 1,
  priority SMALLINT NOT NULL DEFAULT 2,
  profile_level SMALLINT NOT NULL DEFAULT 0,
  level_reason TEXT NOT NULL DEFAULT '',
  refresh_weight INTEGER NOT NULL DEFAULT 0,
  source_kind SMALLINT NOT NULL DEFAULT 0,
  source_id BIGINT NOT NULL DEFAULT 0,
  status_reason TEXT NOT NULL DEFAULT '',
  expires_at TIMESTAMPTZ NULL,
  superseded_by_id BIGINT NOT NULL DEFAULT 0,
  profile_date TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (batch_id, id)
)`, r.maintenanceQualifiedTable("vmm_profile_nodes_trash"), r.recycleBatchesTable())},
		{name: "idx_vmm_management_session_states_status", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_management_session_states_status ON %s (status, updated_at, session_id)`, r.maintenanceQualifiedTable("vmm_management_session_states"))},
		{name: "idx_vmm_management_previews_expiry", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_management_previews_expiry ON %s (expires_at, preview_token)`, r.maintenanceQualifiedTable("vmm_management_previews"))},
		{name: "idx_vmm_management_operations_status", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_management_operations_status ON %s (status, updated_at, operation_id)`, r.maintenanceQualifiedTable("vmm_management_operations"))},
		{name: "idx_vmm_management_recycle_batches_state", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_management_recycle_batches_state ON %s (state, batch_id)`, r.maintenanceQualifiedTable("vmm_management_recycle_batches"))},
		{name: "idx_vmm_sessions_trash_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_trash_batch ON %s (batch_id, id)`, r.maintenanceQualifiedTable("vmm_sessions_trash"))},
		{name: "idx_vmm_profile_nodes_trash_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_trash_batch ON %s (batch_id, id)`, r.maintenanceQualifiedTable("vmm_profile_nodes_trash"))},
	}
}

// postgresSchemaObjectBootstrapError attaches the named table DDL label to startup schema errors so operators can repair the exact failed object.
// postgresSchemaObjectBootstrapError 用于把命名表 DDL 标签附加到启动 schema 错误中，方便运维人员修复具体失败对象。
func postgresSchemaObjectBootstrapError(statement postgresDDLStatement, err error) error {
	return postgresDDLStatementExecutionError("bootstrap postgres schema object", statement, err)
}

// postgresDDLStatement names one schema bootstrap statement so startup failures can identify the exact table or index that failed.
// postgresDDLStatement 用于命名一条 schema 启动语句，让启动失败能够定位到具体失败的表或索引。
type postgresDDLStatement struct {
	// name is the stable diagnostic label for this DDL statement.
	// name 是这条 DDL 语句用于诊断的稳定标签。
	name string
	// sql is the rendered PostgreSQL statement executed during schema bootstrap.
	// sql 是 schema 启动阶段执行的 PostgreSQL 语句。
	sql string
}

// postgresDDLStatementExecutionError attaches a phase and DDL label to one PostgreSQL schema error while preserving the original storage error.
// postgresDDLStatementExecutionError 用于把阶段名和 DDL 标签附加到 PostgreSQL schema 错误上，同时保留原始存储错误。
func postgresDDLStatementExecutionError(phase string, statement postgresDDLStatement, err error) error {
	if err == nil {
		return nil
	}
	return fmt.Errorf("%s %s: %w", strings.TrimSpace(phase), strings.TrimSpace(statement.name), err)
}

// ensureCommonIndexes creates the shared non-lexical indexes reused by both PostgreSQL dialect flavors.
// ensureCommonIndexes 用于创建两种 PostgreSQL 方言都会复用的非 lexical 公共索引。
func (r *maintenanceRepository) ensureCommonIndexes(ctx context.Context) error {
	for _, statement := range postgresCommonIndexStatements(r) {
		if _, err := r.shared.pool.Exec(ctx, strings.TrimSpace(statement.sql)); err != nil {
			return postgresDDLStatementExecutionError("create postgres common index", statement, err)
		}
	}
	return nil
}

// postgresCommonIndexStatements renders the shared index DDL with explicit names so bootstrap errors and tests can trace each statement deterministically.
// postgresCommonIndexStatements 用于渲染带显式名称的共享索引 DDL，让启动错误和测试都能确定性追踪每条语句。
func postgresCommonIndexStatements(r *maintenanceRepository) []postgresDDLStatement {
	return []postgresDDLStatement{
		{name: "idx_vmm_noise_embeddings_lookup", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_noise_embeddings_lookup ON %s (scope, language, model, dimension, rules_hash, category_name, phrase)`, r.noiseEmbeddingsTable())},
		{name: "idx_vmm_sessions_scope", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_scope ON %s (user_id, team_id, space_id, project_id, updated_at DESC)`, r.sessionsTable())},
		{name: "idx_vmm_sessions_project_session", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_project_session ON %s (project_id, session_key)`, r.sessionsTable())},
		{name: "idx_vmm_sessions_compact_boundary", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_sessions_compact_boundary ON %s (project_id, last_compacted_turn_id, id)`, r.sessionsTable())},
		{name: "idx_vmm_turn_records_session", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_session ON %s (session_id, id)`, r.turnsTable())},
		{name: "idx_vmm_turn_records_project_status", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_project_status ON %s (project_id, extracted_status, id)`, r.turnsTable())},
		{name: "idx_vmm_memory_nodes_project_active_window", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_project_active_window ON %s (project_id, memory_status, expires_at, id)`, r.memoryNodesTable())},
		{name: "idx_vmm_memory_nodes_source_turn", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_source_turn ON %s (source_turn_id, id)`, r.memoryNodesTable())},
		{name: "idx_vmm_memory_nodes_origin_session_active", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_origin_session_active ON %s (origin_session_id, memory_status, expires_at, id)`, r.memoryNodesTable())},
		{name: "idx_vmm_memory_nodes_dedupe_window", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_dedupe_window ON %s (origin_session_id, project_id, user_id, source_kind, scope_level, dedupe_hash, memory_status, expires_at, created_at DESC)`, r.memoryNodesTable())},
		{name: "idx_vmm_memory_context_edges_lookup", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_lookup ON %s (context_key, context_value, memory_id)`, r.memoryContextEdgesTable())},
		{name: "idx_vmm_memory_context_edges_memory", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_memory ON %s (memory_id)`, r.memoryContextEdgesTable())},
		{name: "idx_vmm_profile_nodes_bind_status", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_bind_status ON %s (profile_type, bind_id, profile_status, id)`, r.profileNodesTable())},
		{name: "idx_vmm_profile_nodes_active_window", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_active_window ON %s (profile_type, bind_id, profile_status, expires_at, id)`, r.profileNodesTable())},
		{name: "idx_vmm_profile_nodes_turn", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_nodes_turn ON %s (turn_id, id)`, r.profileNodesTable())},
		{name: "idx_vmm_profile_instructions_target", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_profile_instructions_target ON %s (profile_type, bind_id, id)`, r.profileInstructionsTable())},
		{name: "idx_vmm_recycle_batches_lookup", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_batches_lookup ON %s (recycle_type, recycled_at, id)`, r.recycleBatchesTable())},
		{name: "idx_vmm_recycle_batches_session", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_batches_session ON %s (session_id, project_id, id)`, r.recycleBatchesTable())},
		{name: "idx_vmm_recycle_jobs_pending", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_jobs_pending ON %s (job_type, next_run_at, id)`, r.recycleJobsTable())},
		{name: "idx_vmm_recycle_jobs_session", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_recycle_jobs_session ON %s (session_id, project_id, id)`, r.recycleJobsTable())},
		{name: "idx_vmm_memory_nodes_trash_recycled", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_trash_recycled ON %s (recycled_at, batch_id, id)`, r.memoryNodesTrashTable())},
		{name: "idx_vmm_memory_nodes_trash_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_nodes_trash_batch ON %s (batch_id, id)`, r.memoryNodesTrashTable())},
		{name: "idx_vmm_memory_context_edges_trash_recycled", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_trash_recycled ON %s (recycled_at, batch_id, memory_id)`, r.memoryContextEdgesTrashTable())},
		{name: "idx_vmm_memory_context_edges_trash_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_memory_context_edges_trash_batch ON %s (batch_id, memory_id)`, r.memoryContextEdgesTrashTable())},
		{name: "idx_vmm_turn_records_trash_recycled", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_trash_recycled ON %s (recycled_at, batch_id, id)`, r.turnsTrashTable())},
		{name: "idx_vmm_turn_records_trash_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_turn_records_trash_batch ON %s (batch_id, session_id, id)`, r.turnsTrashTable())},
		{name: "idx_vmm_vector_gc_jobs_pending", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_vector_gc_jobs_pending ON %s (completed_at, next_run_at, id)`, r.vectorGCJobsTable())},
		{name: "idx_vmm_vector_gc_jobs_batch", sql: fmt.Sprintf(`CREATE INDEX IF NOT EXISTS idx_vmm_vector_gc_jobs_batch ON %s (batch_id, id)`, r.vectorGCJobsTable())},
	}
}

// ensureVectorIndex creates the shared pgvector ANN index used by both flavors for first-stage semantic recall.
// ensureVectorIndex 用于创建两种方言共享的 pgvector ANN 索引，服务首阶段语义召回。
func (r *maintenanceRepository) ensureVectorIndex(ctx context.Context) error {
	statement := buildMemoryVectorIndexSQL(r.memoryNodesTable(), r.shared.cfg.VectorLists)
	if _, err := r.shared.pool.Exec(ctx, strings.TrimSpace(statement)); err != nil {
		return fmt.Errorf("create postgres vector index: %w", err)
	}
	return nil
}

// buildMemoryVectorIndexSQL renders the shared ANN index DDL so startup bootstrap and maintenance rebuilds always recreate the same pgvector index definition.
// buildMemoryVectorIndexSQL 用于渲染共享 ANN 索引 DDL，确保启动期初始化与维护期重建始终复用同一份 pgvector 索引定义。
func buildMemoryVectorIndexSQL(memoryTable string, lists int) string {
	return fmt.Sprintf(`
CREATE INDEX IF NOT EXISTS %s ON %s USING ivfflat (embedding vector_cosine_ops) WITH (lists = %d)
`, quoteIdentifier("idx_vmm_memory_nodes_embedding_ivfflat"), memoryTable, lists)
}

// ensureDebugSeedWorkspace inserts the deterministic default user/team/space/project rows expected by local debugging flows.
// ensureDebugSeedWorkspace 用于插入本地调试流期望的确定性默认 user/team/space/project 行。
func (r *maintenanceRepository) ensureDebugSeedWorkspace(ctx context.Context) error {
	if r == nil || r.shared == nil || r.shared.pool == nil {
		return fmt.Errorf("postgres store is not initialized")
	}
	var projectCount int
	countSQL := fmt.Sprintf(`SELECT COUNT(*) FROM %s`, r.projectsTable())
	if err := r.shared.pool.QueryRow(ctx, countSQL).Scan(&projectCount); err != nil {
		return fmt.Errorf("count postgres projects before debug seed bootstrap: %w", err)
	}
	if !shouldSeedDebugWorkspace(projectCount) {
		return nil
	}
	now := time.Now().UTC()
	if _, err := r.upsertDebugSeedUser(ctx, r.shared.pool, logicdomain.DefaultWorkspaceResourceName, now); err != nil {
		return err
	}
	teamID, err := r.upsertDebugSeedTeam(ctx, r.shared.pool, logicdomain.DefaultWorkspaceResourceName, now)
	if err != nil {
		return err
	}
	spaceID, err := r.upsertDebugSeedSpace(ctx, r.shared.pool, teamID, logicdomain.DefaultWorkspaceResourceName, now)
	if err != nil {
		return err
	}
	if _, err := r.upsertDebugSeedProject(ctx, r.shared.pool, teamID, spaceID, logicdomain.DefaultWorkspaceResourceName, now); err != nil {
		return err
	}
	return nil
}

// shouldSeedDebugWorkspace reports whether startup should inject the deterministic default hierarchy, matching SQLite by seeding only truly empty workspaces.
// shouldSeedDebugWorkspace 用于判断启动时是否应注入确定性的默认层级；其语义与 SQLite 保持一致，只在工作区真正为空时补种。
func shouldSeedDebugWorkspace(projectCount int) bool {
	return projectCount == 0
}

// upsertDebugSeedUser resolves or creates the default debug user by name so empty workspaces with restored ids can still bootstrap safely.
// upsertDebugSeedUser 用于按名称解析或创建默认调试用户，确保即使空工作区里的 id 已被恢复过，启动也能安全补种。
func (r *maintenanceRepository) upsertDebugSeedUser(ctx context.Context, q profileQueryer, userName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (name, profile, delete_confirm_code, created_at, updated_at)
VALUES ($1, '', '', $2, $2)
ON CONFLICT (name)
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`, r.usersTable())
	var userID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), strings.TrimSpace(userName), now.UTC()).Scan(&userID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed user: %w", err)
	}
	return userID, nil
}

// upsertDebugSeedTeam resolves or creates the default debug team by its stable business key so startup does not depend on one hard-coded row id.
// upsertDebugSeedTeam 用于按稳定的业务键解析或创建默认调试 team，避免启动逻辑依赖单个硬编码行 id。
func (r *maintenanceRepository) upsertDebugSeedTeam(ctx context.Context, q profileQueryer, teamName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (name, profile, created_at, updated_at)
VALUES ($1, '', $2, $2)
ON CONFLICT (name)
DO UPDATE SET name = EXCLUDED.name
RETURNING id
`, r.teamsTable())
	var teamID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), strings.TrimSpace(teamName), now.UTC()).Scan(&teamID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed team: %w", err)
	}
	return teamID, nil
}

// upsertDebugSeedSpace resolves or creates the default debug space under the resolved team so restored name collisions cannot break empty-workspace bootstrap.
// upsertDebugSeedSpace 用于在已解析 team 下解析或创建默认调试 space，避免恢复数据后的同名冲突打断空工作区补种。
func (r *maintenanceRepository) upsertDebugSeedSpace(ctx context.Context, q profileQueryer, teamID uint64, spaceName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (team_id, name, profile, created_at, updated_at)
VALUES ($1, $2, '', $3, $3)
ON CONFLICT (team_id, name)
DO UPDATE SET team_id = EXCLUDED.team_id
RETURNING id
`, r.spacesTable())
	var spaceID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), int64(teamID), strings.TrimSpace(spaceName), now.UTC()).Scan(&spaceID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed space: %w", err)
	}
	return spaceID, nil
}

// upsertDebugSeedProject resolves or creates the default debug project under the resolved Team/Space path so startup keeps one stable default hierarchy by name.
// upsertDebugSeedProject 用于在已解析的 Team/Space 路径下解析或创建默认调试项目，保证启动时按名称维持一条稳定的默认层级。
func (r *maintenanceRepository) upsertDebugSeedProject(ctx context.Context, q profileQueryer, teamID, spaceID uint64, projectName string, now time.Time) (uint64, error) {
	sqlText := fmt.Sprintf(`
INSERT INTO %s (team_id, space_id, name, profile, created_at, updated_at)
VALUES ($1, $2, $3, '', $4, $4)
ON CONFLICT (space_id, name)
DO UPDATE SET team_id = EXCLUDED.team_id, space_id = EXCLUDED.space_id
RETURNING id
`, r.projectsTable())
	var projectID uint64
	if err := q.QueryRow(ctx, strings.TrimSpace(sqlText), int64(teamID), int64(spaceID), strings.TrimSpace(projectName), now.UTC()).Scan(&projectID); err != nil {
		return 0, fmt.Errorf("upsert postgres debug seed project: %w", err)
	}
	return projectID, nil
}

// syncDebugSeedSequences advances identity sequences after debug-seed upserts so later auto-generated ids stay aligned with the current table maxima.
// syncDebugSeedSequences 用于在调试种子 upsert 完成后推进 identity sequence，确保后续自动 id 与当前表内最大值保持对齐。
func (r *maintenanceRepository) syncDebugSeedSequences(ctx context.Context) error {
	for _, tableName := range []string{"vmm_users", "vmm_teams", "vmm_spaces", "vmm_projects", "vmm_sessions", "vmm_turn_records", "vmm_memory_nodes", "vmm_profile_nodes", "vmm_profile_instructions"} {
		if err := r.syncIdentitySequence(ctx, tableName); err != nil {
			return err
		}
	}
	return nil
}

// syncIdentitySequence aligns one table identity sequence with the current MAX(id) so manual seed rows and later auto ids can coexist safely.
// syncIdentitySequence 用于让某张表的 identity sequence 与当前 MAX(id) 对齐，确保手工种子行和后续自动 id 能安全共存。
func (r *maintenanceRepository) syncIdentitySequence(ctx context.Context, tableName string) error {
	statement := fmt.Sprintf(`
SELECT setval(
	pg_get_serial_sequence($1, 'id'),
	GREATEST(COALESCE((SELECT MAX(id) FROM %s), 1), 1),
	true
)
`, r.maintenanceQualifiedTable(tableName))
	if _, err := r.shared.pool.Exec(ctx, strings.TrimSpace(statement), r.maintenanceQualifiedTable(tableName)); err != nil {
		return fmt.Errorf("sync postgres identity sequence for %s: %w", tableName, err)
	}
	return nil
}
