// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: internal/adapters/inbound/grpcapi/proto/v1/vmm.proto

package vmmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthzResponse returns the runtime status plus trace metadata.
// HealthzResponse 用于返回运行状态和 trace 元数据。
type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{0}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthzResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ProjectEntry transports one canonical project node plus its display path.
// ProjectEntry 用于承载一个标准项目节点及其展示路径。
type ProjectEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     uint64                 `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	TeamId        uint64                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SpaceId       uint64                 `protobuf:"varint,3,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	TeamName      string                 `protobuf:"bytes,4,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	SpaceName     string                 `protobuf:"bytes,5,opt,name=space_name,json=spaceName,proto3" json:"space_name,omitempty"`
	ProjectName   string                 `protobuf:"bytes,6,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	DisplayPath   string                 `protobuf:"bytes,7,opt,name=display_path,json=displayPath,proto3" json:"display_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectEntry) Reset() {
	*x = ProjectEntry{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectEntry) ProtoMessage() {}

func (x *ProjectEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectEntry.ProtoReflect.Descriptor instead.
func (*ProjectEntry) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectEntry) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ProjectEntry) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ProjectEntry) GetSpaceId() uint64 {
	if x != nil {
		return x.SpaceId
	}
	return 0
}

func (x *ProjectEntry) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *ProjectEntry) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *ProjectEntry) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectEntry) GetDisplayPath() string {
	if x != nil {
		return x.DisplayPath
	}
	return ""
}

// UserEntry transports one durable user row.
// UserEntry 用于承载一条长期用户记录。
type UserEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEntry) Reset() {
	*x = UserEntry{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntry) ProtoMessage() {}

func (x *UserEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntry.ProtoReflect.Descriptor instead.
func (*UserEntry) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{2}
}

func (x *UserEntry) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserEntry) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// ListProjectsResponse returns all projects plus trace metadata.
// ListProjectsResponse 用于返回全部项目和 trace 元数据。
type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectEntry        `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{3}
}

func (x *ListProjectsResponse) GetProjects() []*ProjectEntry {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ListProjectsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ResolveProjectRequest accepts either a numeric project id or one canonical Team/Space/Project path.
// ResolveProjectRequest 用于接收数字 project id，或标准 Team/Space/Project 路径。
type ResolveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectRef    string                 `protobuf:"bytes,1,opt,name=project_ref,json=projectRef,proto3" json:"project_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProjectRequest) Reset() {
	*x = ResolveProjectRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProjectRequest) ProtoMessage() {}

func (x *ResolveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProjectRequest.ProtoReflect.Descriptor instead.
func (*ResolveProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveProjectRequest) GetProjectRef() string {
	if x != nil {
		return x.ProjectRef
	}
	return ""
}

// ResolveProjectResponse returns the resolved canonical project node and a stable status message.
// ResolveProjectResponse 用于返回解析后的标准项目节点和稳定状态消息。
type ResolveProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectEntry          `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProjectResponse) Reset() {
	*x = ResolveProjectResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProjectResponse) ProtoMessage() {}

func (x *ResolveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProjectResponse.ProtoReflect.Descriptor instead.
func (*ResolveProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveProjectResponse) GetProject() *ProjectEntry {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ResolveProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResolveProjectResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// EnsureProjectRequest asks the server to resolve or create one canonical Team/Space/Project path.
// EnsureProjectRequest 用于请求服务端解析或创建一个标准 Team/Space/Project 路径。
type EnsureProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	ConfirmCreate bool                   `protobuf:"varint,2,opt,name=confirm_create,json=confirmCreate,proto3" json:"confirm_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureProjectRequest) Reset() {
	*x = EnsureProjectRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureProjectRequest) ProtoMessage() {}

func (x *EnsureProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureProjectRequest.ProtoReflect.Descriptor instead.
func (*EnsureProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{6}
}

func (x *EnsureProjectRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *EnsureProjectRequest) GetConfirmCreate() bool {
	if x != nil {
		return x.ConfirmCreate
	}
	return false
}

// EnsureProjectResponse returns the project node plus creation/confirmation state.
// EnsureProjectResponse 用于返回项目节点，以及创建或确认状态。
type EnsureProjectResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Project        *ProjectEntry          `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Exists         bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	NeedsConfirm   bool                   `protobuf:"varint,4,opt,name=needs_confirm,json=needsConfirm,proto3" json:"needs_confirm,omitempty"`
	CreatedTeam    bool                   `protobuf:"varint,5,opt,name=created_team,json=createdTeam,proto3" json:"created_team,omitempty"`
	CreatedSpace   bool                   `protobuf:"varint,6,opt,name=created_space,json=createdSpace,proto3" json:"created_space,omitempty"`
	CreatedProject bool                   `protobuf:"varint,7,opt,name=created_project,json=createdProject,proto3" json:"created_project,omitempty"`
	MissingTeam    bool                   `protobuf:"varint,8,opt,name=missing_team,json=missingTeam,proto3" json:"missing_team,omitempty"`
	MissingSpace   bool                   `protobuf:"varint,9,opt,name=missing_space,json=missingSpace,proto3" json:"missing_space,omitempty"`
	TraceId        string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnsureProjectResponse) Reset() {
	*x = EnsureProjectResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureProjectResponse) ProtoMessage() {}

func (x *EnsureProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureProjectResponse.ProtoReflect.Descriptor instead.
func (*EnsureProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{7}
}

func (x *EnsureProjectResponse) GetProject() *ProjectEntry {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *EnsureProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnsureProjectResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *EnsureProjectResponse) GetNeedsConfirm() bool {
	if x != nil {
		return x.NeedsConfirm
	}
	return false
}

func (x *EnsureProjectResponse) GetCreatedTeam() bool {
	if x != nil {
		return x.CreatedTeam
	}
	return false
}

func (x *EnsureProjectResponse) GetCreatedSpace() bool {
	if x != nil {
		return x.CreatedSpace
	}
	return false
}

func (x *EnsureProjectResponse) GetCreatedProject() bool {
	if x != nil {
		return x.CreatedProject
	}
	return false
}

func (x *EnsureProjectResponse) GetMissingTeam() bool {
	if x != nil {
		return x.MissingTeam
	}
	return false
}

func (x *EnsureProjectResponse) GetMissingSpace() bool {
	if x != nil {
		return x.MissingSpace
	}
	return false
}

func (x *EnsureProjectResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// DeleteProjectRequest identifies the target project path and whether deletion has been explicitly confirmed.
// DeleteProjectRequest 用于标识目标项目路径，以及删除是否已经显式确认。
type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	ConfirmDelete bool                   `protobuf:"varint,2,opt,name=confirm_delete,json=confirmDelete,proto3" json:"confirm_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProjectRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *DeleteProjectRequest) GetConfirmDelete() bool {
	if x != nil {
		return x.ConfirmDelete
	}
	return false
}

// DeleteProjectResponse returns deletion counts, confirmation status, and the affected project.
// DeleteProjectResponse 用于返回删除计数、确认状态以及受影响项目。
type DeleteProjectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Project           *ProjectEntry          `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NeedsConfirm      bool                   `protobuf:"varint,3,opt,name=needs_confirm,json=needsConfirm,proto3" json:"needs_confirm,omitempty"`
	DeletedSessions   int64                  `protobuf:"varint,4,opt,name=deleted_sessions,json=deletedSessions,proto3" json:"deleted_sessions,omitempty"`
	DeletedMessages   int64                  `protobuf:"varint,5,opt,name=deleted_messages,json=deletedMessages,proto3" json:"deleted_messages,omitempty"`
	DeletedMemories   int64                  `protobuf:"varint,6,opt,name=deleted_memories,json=deletedMemories,proto3" json:"deleted_memories,omitempty"`
	DeletedVectorRows uint64                 `protobuf:"varint,7,opt,name=deleted_vector_rows,json=deletedVectorRows,proto3" json:"deleted_vector_rows,omitempty"`
	TraceId           string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteProjectResponse) Reset() {
	*x = DeleteProjectResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectResponse) ProtoMessage() {}

func (x *DeleteProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteProjectResponse) GetProject() *ProjectEntry {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *DeleteProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteProjectResponse) GetNeedsConfirm() bool {
	if x != nil {
		return x.NeedsConfirm
	}
	return false
}

func (x *DeleteProjectResponse) GetDeletedSessions() int64 {
	if x != nil {
		return x.DeletedSessions
	}
	return 0
}

func (x *DeleteProjectResponse) GetDeletedMessages() int64 {
	if x != nil {
		return x.DeletedMessages
	}
	return 0
}

func (x *DeleteProjectResponse) GetDeletedMemories() int64 {
	if x != nil {
		return x.DeletedMemories
	}
	return 0
}

func (x *DeleteProjectResponse) GetDeletedVectorRows() uint64 {
	if x != nil {
		return x.DeletedVectorRows
	}
	return 0
}

func (x *DeleteProjectResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// MigrateProjectRequest identifies the source and target project paths plus the explicit migration confirmation flag.
// MigrateProjectRequest 用于标识源/目标项目路径，以及显式迁移确认标记。
type MigrateProjectRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceProjectPath string                 `protobuf:"bytes,1,opt,name=source_project_path,json=sourceProjectPath,proto3" json:"source_project_path,omitempty"`
	TargetProjectPath string                 `protobuf:"bytes,2,opt,name=target_project_path,json=targetProjectPath,proto3" json:"target_project_path,omitempty"`
	ConfirmMigrate    bool                   `protobuf:"varint,3,opt,name=confirm_migrate,json=confirmMigrate,proto3" json:"confirm_migrate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MigrateProjectRequest) Reset() {
	*x = MigrateProjectRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateProjectRequest) ProtoMessage() {}

func (x *MigrateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateProjectRequest.ProtoReflect.Descriptor instead.
func (*MigrateProjectRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{10}
}

func (x *MigrateProjectRequest) GetSourceProjectPath() string {
	if x != nil {
		return x.SourceProjectPath
	}
	return ""
}

func (x *MigrateProjectRequest) GetTargetProjectPath() string {
	if x != nil {
		return x.TargetProjectPath
	}
	return ""
}

func (x *MigrateProjectRequest) GetConfirmMigrate() bool {
	if x != nil {
		return x.ConfirmMigrate
	}
	return false
}

// MigrateProjectResponse returns migration counts, confirmation status, and both source/target project nodes.
// MigrateProjectResponse 用于返回迁移计数、确认状态，以及源/目标项目节点。
type MigrateProjectResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SourceProject     *ProjectEntry          `protobuf:"bytes,1,opt,name=source_project,json=sourceProject,proto3" json:"source_project,omitempty"`
	TargetProject     *ProjectEntry          `protobuf:"bytes,2,opt,name=target_project,json=targetProject,proto3" json:"target_project,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	NeedsConfirm      bool                   `protobuf:"varint,4,opt,name=needs_confirm,json=needsConfirm,proto3" json:"needs_confirm,omitempty"`
	MigratedSessions  int64                  `protobuf:"varint,5,opt,name=migrated_sessions,json=migratedSessions,proto3" json:"migrated_sessions,omitempty"`
	MigratedMessages  int64                  `protobuf:"varint,6,opt,name=migrated_messages,json=migratedMessages,proto3" json:"migrated_messages,omitempty"`
	MigratedMemories  int64                  `protobuf:"varint,7,opt,name=migrated_memories,json=migratedMemories,proto3" json:"migrated_memories,omitempty"`
	RebuiltVectorRows int64                  `protobuf:"varint,8,opt,name=rebuilt_vector_rows,json=rebuiltVectorRows,proto3" json:"rebuilt_vector_rows,omitempty"`
	TraceId           string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MigrateProjectResponse) Reset() {
	*x = MigrateProjectResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateProjectResponse) ProtoMessage() {}

func (x *MigrateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateProjectResponse.ProtoReflect.Descriptor instead.
func (*MigrateProjectResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{11}
}

func (x *MigrateProjectResponse) GetSourceProject() *ProjectEntry {
	if x != nil {
		return x.SourceProject
	}
	return nil
}

func (x *MigrateProjectResponse) GetTargetProject() *ProjectEntry {
	if x != nil {
		return x.TargetProject
	}
	return nil
}

func (x *MigrateProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MigrateProjectResponse) GetNeedsConfirm() bool {
	if x != nil {
		return x.NeedsConfirm
	}
	return false
}

func (x *MigrateProjectResponse) GetMigratedSessions() int64 {
	if x != nil {
		return x.MigratedSessions
	}
	return 0
}

func (x *MigrateProjectResponse) GetMigratedMessages() int64 {
	if x != nil {
		return x.MigratedMessages
	}
	return 0
}

func (x *MigrateProjectResponse) GetMigratedMemories() int64 {
	if x != nil {
		return x.MigratedMemories
	}
	return 0
}

func (x *MigrateProjectResponse) GetRebuiltVectorRows() int64 {
	if x != nil {
		return x.RebuiltVectorRows
	}
	return 0
}

func (x *MigrateProjectResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ResolveUserRequest accepts either a numeric user id or a user name and can optionally create a missing user.
// ResolveUserRequest 用于接收数字 user id 或用户名，并在需要时创建缺失用户。
type ResolveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserRef       string                 `protobuf:"bytes,1,opt,name=user_ref,json=userRef,proto3" json:"user_ref,omitempty"`
	ConfirmCreate bool                   `protobuf:"varint,2,opt,name=confirm_create,json=confirmCreate,proto3" json:"confirm_create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUserRequest) Reset() {
	*x = ResolveUserRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUserRequest) ProtoMessage() {}

func (x *ResolveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveUserRequest) GetUserRef() string {
	if x != nil {
		return x.UserRef
	}
	return ""
}

func (x *ResolveUserRequest) GetConfirmCreate() bool {
	if x != nil {
		return x.ConfirmCreate
	}
	return false
}

// ResolveUserResponse returns the resolved user row and creation/existence status.
// ResolveUserResponse 用于返回解析后的用户记录，以及创建/存在状态。
type ResolveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserEntry             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Exists        bool                   `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveUserResponse) Reset() {
	*x = ResolveUserResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUserResponse) ProtoMessage() {}

func (x *ResolveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUserResponse.ProtoReflect.Descriptor instead.
func (*ResolveUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveUserResponse) GetUser() *UserEntry {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ResolveUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResolveUserResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *ResolveUserResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ResolveUserResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ListUsersResponse returns all durable users plus trace metadata.
// ListUsersResponse 用于返回全部长期用户和 trace 元数据。
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserEntry           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersResponse) GetUsers() []*UserEntry {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// DeleteUserRequest carries the user reference and the generated confirmation code for protected deletion.
// DeleteUserRequest 用于承载用户引用和受保护删除所需的确认码。
type DeleteUserRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserRef          string                 `protobuf:"bytes,1,opt,name=user_ref,json=userRef,proto3" json:"user_ref,omitempty"`
	ConfirmationCode string                 `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserRequest) GetUserRef() string {
	if x != nil {
		return x.UserRef
	}
	return ""
}

func (x *DeleteUserRequest) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

// DeleteUserResponse returns deletion counts, confirmation state, and the user row involved in the flow.
// DeleteUserResponse 用于返回删除计数、确认状态，以及流程涉及的用户记录。
type DeleteUserResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	User                 *UserEntry             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequiresConfirmation bool                   `protobuf:"varint,3,opt,name=requires_confirmation,json=requiresConfirmation,proto3" json:"requires_confirmation,omitempty"`
	ConfirmationCode     string                 `protobuf:"bytes,4,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	DeletedSessions      int64                  `protobuf:"varint,5,opt,name=deleted_sessions,json=deletedSessions,proto3" json:"deleted_sessions,omitempty"`
	DeletedMessages      int64                  `protobuf:"varint,6,opt,name=deleted_messages,json=deletedMessages,proto3" json:"deleted_messages,omitempty"`
	DeletedMemories      int64                  `protobuf:"varint,7,opt,name=deleted_memories,json=deletedMemories,proto3" json:"deleted_memories,omitempty"`
	DeletedVectorRows    uint64                 `protobuf:"varint,8,opt,name=deleted_vector_rows,json=deletedVectorRows,proto3" json:"deleted_vector_rows,omitempty"`
	TraceId              string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteUserResponse) GetUser() *UserEntry {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteUserResponse) GetRequiresConfirmation() bool {
	if x != nil {
		return x.RequiresConfirmation
	}
	return false
}

func (x *DeleteUserResponse) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *DeleteUserResponse) GetDeletedSessions() int64 {
	if x != nil {
		return x.DeletedSessions
	}
	return 0
}

func (x *DeleteUserResponse) GetDeletedMessages() int64 {
	if x != nil {
		return x.DeletedMessages
	}
	return 0
}

func (x *DeleteUserResponse) GetDeletedMemories() int64 {
	if x != nil {
		return x.DeletedMemories
	}
	return 0
}

func (x *DeleteUserResponse) GetDeletedVectorRows() uint64 {
	if x != nil {
		return x.DeletedVectorRows
	}
	return 0
}

func (x *DeleteUserResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// PreCheckRequest carries only the numeric project/user ids plus the current user text.
// PreCheckRequest 用于只承载数字 project/user id，以及当前用户文本。
type PreCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     uint64                 `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserContent   string                 `protobuf:"bytes,4,opt,name=user_content,json=userContent,proto3" json:"user_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckRequest) Reset() {
	*x = PreCheckRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckRequest) ProtoMessage() {}

func (x *PreCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckRequest.ProtoReflect.Descriptor instead.
func (*PreCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{17}
}

func (x *PreCheckRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreCheckRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PreCheckRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PreCheckRequest) GetUserContent() string {
	if x != nil {
		return x.UserContent
	}
	return ""
}

// ContextItem transports one assembled context item back to the caller.
// ContextItem 用于把一条组装后的上下文项返回给调用方。
type ContextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextItem) Reset() {
	*x = ContextItem{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextItem) ProtoMessage() {}

func (x *ContextItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextItem.ProtoReflect.Descriptor instead.
func (*ContextItem) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{18}
}

func (x *ContextItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContextItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContextItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContextItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PreCheckResponse returns the injection decision and assembled context payload.
// PreCheckResponse 用于返回注入决策和组装后的上下文载荷。
type PreCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldInject  bool                   `protobuf:"varint,1,opt,name=should_inject,json=shouldInject,proto3" json:"should_inject,omitempty"`
	ContextText   string                 `protobuf:"bytes,2,opt,name=context_text,json=contextText,proto3" json:"context_text,omitempty"`
	ContextItems  []*ContextItem         `protobuf:"bytes,3,rep,name=context_items,json=contextItems,proto3" json:"context_items,omitempty"`
	Degraded      bool                   `protobuf:"varint,4,opt,name=degraded,proto3" json:"degraded,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckResponse) Reset() {
	*x = PreCheckResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckResponse) ProtoMessage() {}

func (x *PreCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckResponse.ProtoReflect.Descriptor instead.
func (*PreCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{19}
}

func (x *PreCheckResponse) GetShouldInject() bool {
	if x != nil {
		return x.ShouldInject
	}
	return false
}

func (x *PreCheckResponse) GetContextText() string {
	if x != nil {
		return x.ContextText
	}
	return ""
}

func (x *PreCheckResponse) GetContextItems() []*ContextItem {
	if x != nil {
		return x.ContextItems
	}
	return nil
}

func (x *PreCheckResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *PreCheckResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// PostActionTimelineItem carries one middle timeline node from the text-only contract.
// PostActionTimelineItem 用于承载纯文本契约中的一条中间 timeline 节点。
type PostActionTimelineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionTimelineItem) Reset() {
	*x = PostActionTimelineItem{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionTimelineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionTimelineItem) ProtoMessage() {}

func (x *PostActionTimelineItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionTimelineItem.ProtoReflect.Descriptor instead.
func (*PostActionTimelineItem) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{20}
}

func (x *PostActionTimelineItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostActionTimelineItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PostActionRequest carries the new text-only post-action payload.
// PostActionRequest 用于承载新的纯文本 post-action 载荷。
type PostActionRequest struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SessionId        string                    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId           uint64                    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId        uint64                    `protobuf:"varint,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserContent      string                    `protobuf:"bytes,4,opt,name=user_content,json=userContent,proto3" json:"user_content,omitempty"`
	AssistantContent string                    `protobuf:"bytes,5,opt,name=assistant_content,json=assistantContent,proto3" json:"assistant_content,omitempty"`
	Timeline         []*PostActionTimelineItem `protobuf:"bytes,6,rep,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostActionRequest) Reset() {
	*x = PostActionRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionRequest) ProtoMessage() {}

func (x *PostActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionRequest.ProtoReflect.Descriptor instead.
func (*PostActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{21}
}

func (x *PostActionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostActionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostActionRequest) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *PostActionRequest) GetUserContent() string {
	if x != nil {
		return x.UserContent
	}
	return ""
}

func (x *PostActionRequest) GetAssistantContent() string {
	if x != nil {
		return x.AssistantContent
	}
	return ""
}

func (x *PostActionRequest) GetTimeline() []*PostActionTimelineItem {
	if x != nil {
		return x.Timeline
	}
	return nil
}

// PostActionResponse acknowledges whether the request was accepted for background persistence.
// PostActionResponse 用于确认请求是否已被接受并进入后台持久化流程。
type PostActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionResponse) Reset() {
	*x = PostActionResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionResponse) ProtoMessage() {}

func (x *PostActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionResponse.ProtoReflect.Descriptor instead.
func (*PostActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{22}
}

func (x *PostActionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PostActionResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto protoreflect.FileDescriptor

const file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc = "" +
	"\n" +
	"4internal/adapters/inbound/grpcapi/proto/v1/vmm.proto\x12\x06vmm.v1\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\xe3\x01\n" +
	"\fProjectEntry\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\x04R\tprojectId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x04R\x06teamId\x12\x19\n" +
	"\bspace_id\x18\x03 \x01(\x04R\aspaceId\x12\x1b\n" +
	"\tteam_name\x18\x04 \x01(\tR\bteamName\x12\x1d\n" +
	"\n" +
	"space_name\x18\x05 \x01(\tR\tspaceName\x12!\n" +
	"\fproject_name\x18\x06 \x01(\tR\vprojectName\x12!\n" +
	"\fdisplay_path\x18\a \x01(\tR\vdisplayPath\"A\n" +
	"\tUserEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"c\n" +
	"\x14ListProjectsResponse\x120\n" +
	"\bprojects\x18\x01 \x03(\v2\x14.vmm.v1.ProjectEntryR\bprojects\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"8\n" +
	"\x15ResolveProjectRequest\x12\x1f\n" +
	"\vproject_ref\x18\x01 \x01(\tR\n" +
	"projectRef\"}\n" +
	"\x16ResolveProjectResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.vmm.v1.ProjectEntryR\aproject\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"`\n" +
	"\x14EnsureProjectRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12%\n" +
	"\x0econfirm_create\x18\x02 \x01(\bR\rconfirmCreate\"\xf2\x02\n" +
	"\x15EnsureProjectResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.vmm.v1.ProjectEntryR\aproject\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12#\n" +
	"\rneeds_confirm\x18\x04 \x01(\bR\fneedsConfirm\x12!\n" +
	"\fcreated_team\x18\x05 \x01(\bR\vcreatedTeam\x12#\n" +
	"\rcreated_space\x18\x06 \x01(\bR\fcreatedSpace\x12'\n" +
	"\x0fcreated_project\x18\a \x01(\bR\x0ecreatedProject\x12!\n" +
	"\fmissing_team\x18\b \x01(\bR\vmissingTeam\x12#\n" +
	"\rmissing_space\x18\t \x01(\bR\fmissingSpace\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"`\n" +
	"\x14DeleteProjectRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12%\n" +
	"\x0econfirm_delete\x18\x02 \x01(\bR\rconfirmDelete\"\xd2\x02\n" +
	"\x15DeleteProjectResponse\x12.\n" +
	"\aproject\x18\x01 \x01(\v2\x14.vmm.v1.ProjectEntryR\aproject\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rneeds_confirm\x18\x03 \x01(\bR\fneedsConfirm\x12)\n" +
	"\x10deleted_sessions\x18\x04 \x01(\x03R\x0fdeletedSessions\x12)\n" +
	"\x10deleted_messages\x18\x05 \x01(\x03R\x0fdeletedMessages\x12)\n" +
	"\x10deleted_memories\x18\x06 \x01(\x03R\x0fdeletedMemories\x12.\n" +
	"\x13deleted_vector_rows\x18\a \x01(\x04R\x11deletedVectorRows\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\"\xa0\x01\n" +
	"\x15MigrateProjectRequest\x12.\n" +
	"\x13source_project_path\x18\x01 \x01(\tR\x11sourceProjectPath\x12.\n" +
	"\x13target_project_path\x18\x02 \x01(\tR\x11targetProjectPath\x12'\n" +
	"\x0fconfirm_migrate\x18\x03 \x01(\bR\x0econfirmMigrate\"\xa3\x03\n" +
	"\x16MigrateProjectResponse\x12;\n" +
	"\x0esource_project\x18\x01 \x01(\v2\x14.vmm.v1.ProjectEntryR\rsourceProject\x12;\n" +
	"\x0etarget_project\x18\x02 \x01(\v2\x14.vmm.v1.ProjectEntryR\rtargetProject\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rneeds_confirm\x18\x04 \x01(\bR\fneedsConfirm\x12+\n" +
	"\x11migrated_sessions\x18\x05 \x01(\x03R\x10migratedSessions\x12+\n" +
	"\x11migrated_messages\x18\x06 \x01(\x03R\x10migratedMessages\x12+\n" +
	"\x11migrated_memories\x18\a \x01(\x03R\x10migratedMemories\x12.\n" +
	"\x13rebuilt_vector_rows\x18\b \x01(\x03R\x11rebuiltVectorRows\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"V\n" +
	"\x12ResolveUserRequest\x12\x19\n" +
	"\buser_ref\x18\x01 \x01(\tR\auserRef\x12%\n" +
	"\x0econfirm_create\x18\x02 \x01(\bR\rconfirmCreate\"\xa3\x01\n" +
	"\x13ResolveUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.vmm.v1.UserEntryR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x16\n" +
	"\x06exists\x18\x04 \x01(\bR\x06exists\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"W\n" +
	"\x11ListUsersResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.vmm.v1.UserEntryR\x05users\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"[\n" +
	"\x11DeleteUserRequest\x12\x19\n" +
	"\buser_ref\x18\x01 \x01(\tR\auserRef\x12+\n" +
	"\x11confirmation_code\x18\x02 \x01(\tR\x10confirmationCode\"\x83\x03\n" +
	"\x12DeleteUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.vmm.v1.UserEntryR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x15requires_confirmation\x18\x03 \x01(\bR\x14requiresConfirmation\x12+\n" +
	"\x11confirmation_code\x18\x04 \x01(\tR\x10confirmationCode\x12)\n" +
	"\x10deleted_sessions\x18\x05 \x01(\x03R\x0fdeletedSessions\x12)\n" +
	"\x10deleted_messages\x18\x06 \x01(\x03R\x0fdeletedMessages\x12)\n" +
	"\x10deleted_memories\x18\a \x01(\x03R\x0fdeletedMemories\x12.\n" +
	"\x13deleted_vector_rows\x18\b \x01(\x04R\x11deletedVectorRows\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\"\x8b\x01\n" +
	"\x0fPreCheckRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x04R\tprojectId\x12!\n" +
	"\fuser_content\x18\x04 \x01(\tR\vuserContent\"y\n" +
	"\vContextItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"\xcb\x01\n" +
	"\x10PreCheckResponse\x12#\n" +
	"\rshould_inject\x18\x01 \x01(\bR\fshouldInject\x12!\n" +
	"\fcontext_text\x18\x02 \x01(\tR\vcontextText\x128\n" +
	"\rcontext_items\x18\x03 \x03(\v2\x13.vmm.v1.ContextItemR\fcontextItems\x12\x1a\n" +
	"\bdegraded\x18\x04 \x01(\bR\bdegraded\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"F\n" +
	"\x16PostActionTimelineItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf6\x01\n" +
	"\x11PostActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\x04R\tprojectId\x12!\n" +
	"\fuser_content\x18\x04 \x01(\tR\vuserContent\x12+\n" +
	"\x11assistant_content\x18\x05 \x01(\tR\x10assistantContent\x12:\n" +
	"\btimeline\x18\x06 \x03(\v2\x1e.vmm.v1.PostActionTimelineItemR\btimeline\"K\n" +
	"\x12PostActionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId2\x9d\x06\n" +
	"\n" +
	"VMMService\x12:\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x17.vmm.v1.HealthzResponse\x12D\n" +
	"\fListProjects\x12\x16.google.protobuf.Empty\x1a\x1c.vmm.v1.ListProjectsResponse\x12O\n" +
	"\x0eResolveProject\x12\x1d.vmm.v1.ResolveProjectRequest\x1a\x1e.vmm.v1.ResolveProjectResponse\x12L\n" +
	"\rEnsureProject\x12\x1c.vmm.v1.EnsureProjectRequest\x1a\x1d.vmm.v1.EnsureProjectResponse\x12L\n" +
	"\rDeleteProject\x12\x1c.vmm.v1.DeleteProjectRequest\x1a\x1d.vmm.v1.DeleteProjectResponse\x12O\n" +
	"\x0eMigrateProject\x12\x1d.vmm.v1.MigrateProjectRequest\x1a\x1e.vmm.v1.MigrateProjectResponse\x12F\n" +
	"\vResolveUser\x12\x1a.vmm.v1.ResolveUserRequest\x1a\x1b.vmm.v1.ResolveUserResponse\x12>\n" +
	"\tListUsers\x12\x16.google.protobuf.Empty\x1a\x19.vmm.v1.ListUsersResponse\x12C\n" +
	"\n" +
	"DeleteUser\x12\x19.vmm.v1.DeleteUserRequest\x1a\x1a.vmm.v1.DeleteUserResponse\x12=\n" +
	"\bPreCheck\x12\x17.vmm.v1.PreCheckRequest\x1a\x18.vmm.v1.PreCheckResponse\x12C\n" +
	"\n" +
	"PostAction\x12\x19.vmm.v1.PostActionRequest\x1a\x1a.vmm.v1.PostActionResponseBLZJgithub.com/openvulcan/vmm/internal/adapters/inbound/grpcapi/proto/v1;vmmv1b\x06proto3"

var (
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescOnce sync.Once
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData []byte
)

func file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP() []byte {
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescOnce.Do(func() {
		file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc), len(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc)))
	})
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData
}

var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes = []any{
	(*HealthzResponse)(nil),        // 0: vmm.v1.HealthzResponse
	(*ProjectEntry)(nil),           // 1: vmm.v1.ProjectEntry
	(*UserEntry)(nil),              // 2: vmm.v1.UserEntry
	(*ListProjectsResponse)(nil),   // 3: vmm.v1.ListProjectsResponse
	(*ResolveProjectRequest)(nil),  // 4: vmm.v1.ResolveProjectRequest
	(*ResolveProjectResponse)(nil), // 5: vmm.v1.ResolveProjectResponse
	(*EnsureProjectRequest)(nil),   // 6: vmm.v1.EnsureProjectRequest
	(*EnsureProjectResponse)(nil),  // 7: vmm.v1.EnsureProjectResponse
	(*DeleteProjectRequest)(nil),   // 8: vmm.v1.DeleteProjectRequest
	(*DeleteProjectResponse)(nil),  // 9: vmm.v1.DeleteProjectResponse
	(*MigrateProjectRequest)(nil),  // 10: vmm.v1.MigrateProjectRequest
	(*MigrateProjectResponse)(nil), // 11: vmm.v1.MigrateProjectResponse
	(*ResolveUserRequest)(nil),     // 12: vmm.v1.ResolveUserRequest
	(*ResolveUserResponse)(nil),    // 13: vmm.v1.ResolveUserResponse
	(*ListUsersResponse)(nil),      // 14: vmm.v1.ListUsersResponse
	(*DeleteUserRequest)(nil),      // 15: vmm.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 16: vmm.v1.DeleteUserResponse
	(*PreCheckRequest)(nil),        // 17: vmm.v1.PreCheckRequest
	(*ContextItem)(nil),            // 18: vmm.v1.ContextItem
	(*PreCheckResponse)(nil),       // 19: vmm.v1.PreCheckResponse
	(*PostActionTimelineItem)(nil), // 20: vmm.v1.PostActionTimelineItem
	(*PostActionRequest)(nil),      // 21: vmm.v1.PostActionRequest
	(*PostActionResponse)(nil),     // 22: vmm.v1.PostActionResponse
	(*emptypb.Empty)(nil),          // 23: google.protobuf.Empty
}
var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs = []int32{
	1,  // 0: vmm.v1.ListProjectsResponse.projects:type_name -> vmm.v1.ProjectEntry
	1,  // 1: vmm.v1.ResolveProjectResponse.project:type_name -> vmm.v1.ProjectEntry
	1,  // 2: vmm.v1.EnsureProjectResponse.project:type_name -> vmm.v1.ProjectEntry
	1,  // 3: vmm.v1.DeleteProjectResponse.project:type_name -> vmm.v1.ProjectEntry
	1,  // 4: vmm.v1.MigrateProjectResponse.source_project:type_name -> vmm.v1.ProjectEntry
	1,  // 5: vmm.v1.MigrateProjectResponse.target_project:type_name -> vmm.v1.ProjectEntry
	2,  // 6: vmm.v1.ResolveUserResponse.user:type_name -> vmm.v1.UserEntry
	2,  // 7: vmm.v1.ListUsersResponse.users:type_name -> vmm.v1.UserEntry
	2,  // 8: vmm.v1.DeleteUserResponse.user:type_name -> vmm.v1.UserEntry
	18, // 9: vmm.v1.PreCheckResponse.context_items:type_name -> vmm.v1.ContextItem
	20, // 10: vmm.v1.PostActionRequest.timeline:type_name -> vmm.v1.PostActionTimelineItem
	23, // 11: vmm.v1.VMMService.Healthz:input_type -> google.protobuf.Empty
	23, // 12: vmm.v1.VMMService.ListProjects:input_type -> google.protobuf.Empty
	4,  // 13: vmm.v1.VMMService.ResolveProject:input_type -> vmm.v1.ResolveProjectRequest
	6,  // 14: vmm.v1.VMMService.EnsureProject:input_type -> vmm.v1.EnsureProjectRequest
	8,  // 15: vmm.v1.VMMService.DeleteProject:input_type -> vmm.v1.DeleteProjectRequest
	10, // 16: vmm.v1.VMMService.MigrateProject:input_type -> vmm.v1.MigrateProjectRequest
	12, // 17: vmm.v1.VMMService.ResolveUser:input_type -> vmm.v1.ResolveUserRequest
	23, // 18: vmm.v1.VMMService.ListUsers:input_type -> google.protobuf.Empty
	15, // 19: vmm.v1.VMMService.DeleteUser:input_type -> vmm.v1.DeleteUserRequest
	17, // 20: vmm.v1.VMMService.PreCheck:input_type -> vmm.v1.PreCheckRequest
	21, // 21: vmm.v1.VMMService.PostAction:input_type -> vmm.v1.PostActionRequest
	0,  // 22: vmm.v1.VMMService.Healthz:output_type -> vmm.v1.HealthzResponse
	3,  // 23: vmm.v1.VMMService.ListProjects:output_type -> vmm.v1.ListProjectsResponse
	5,  // 24: vmm.v1.VMMService.ResolveProject:output_type -> vmm.v1.ResolveProjectResponse
	7,  // 25: vmm.v1.VMMService.EnsureProject:output_type -> vmm.v1.EnsureProjectResponse
	9,  // 26: vmm.v1.VMMService.DeleteProject:output_type -> vmm.v1.DeleteProjectResponse
	11, // 27: vmm.v1.VMMService.MigrateProject:output_type -> vmm.v1.MigrateProjectResponse
	13, // 28: vmm.v1.VMMService.ResolveUser:output_type -> vmm.v1.ResolveUserResponse
	14, // 29: vmm.v1.VMMService.ListUsers:output_type -> vmm.v1.ListUsersResponse
	16, // 30: vmm.v1.VMMService.DeleteUser:output_type -> vmm.v1.DeleteUserResponse
	19, // 31: vmm.v1.VMMService.PreCheck:output_type -> vmm.v1.PreCheckResponse
	22, // 32: vmm.v1.VMMService.PostAction:output_type -> vmm.v1.PostActionResponse
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_init() }
func file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_init() {
	if File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc), len(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes,
		DependencyIndexes: file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs,
		MessageInfos:      file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes,
	}.Build()
	File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto = out.File
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes = nil
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs = nil
}
