// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: internal/adapters/inbound/grpcapi/proto/v1/vmm.proto

package vmmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthzResponse returns the runtime status plus trace metadata.
// HealthzResponse 用于返回运行状态和 trace 元数据。
type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{0}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthzResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// ChatRequest carries the lightweight scrub-and-store request.
// ChatRequest 用于承载轻量的脱敏归档请求。
type ChatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptLanguage string                 `protobuf:"bytes,3,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

// ChatResponse returns the scrubbed message stored by the archive flow.
// ChatResponse 用于返回归档流程存储的脱敏消息。
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatResponse) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ChatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// PreCheckRequest carries the simplified current-turn memory lookup request.
// PreCheckRequest 用于承载简化后的当前轮记忆检索请求。
type PreCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SpaceId       string                 `protobuf:"bytes,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserContent   string                 `protobuf:"bytes,6,opt,name=user_content,json=userContent,proto3" json:"user_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckRequest) Reset() {
	*x = PreCheckRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckRequest) ProtoMessage() {}

func (x *PreCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckRequest.ProtoReflect.Descriptor instead.
func (*PreCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{3}
}

func (x *PreCheckRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PreCheckRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreCheckRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *PreCheckRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PreCheckRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PreCheckRequest) GetUserContent() string {
	if x != nil {
		return x.UserContent
	}
	return ""
}

// ContextItem transports one assembled context item back to the caller.
// ContextItem 用于把一条组装后的上下文项返回给调用方。
type ContextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextItem) Reset() {
	*x = ContextItem{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextItem) ProtoMessage() {}

func (x *ContextItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextItem.ProtoReflect.Descriptor instead.
func (*ContextItem) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{4}
}

func (x *ContextItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContextItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContextItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ContextItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContextItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// PreCheckResponse returns the injection decision and assembled context payload.
// PreCheckResponse 用于返回注入决策和组装后的上下文载荷。
type PreCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShouldInject  bool                   `protobuf:"varint,1,opt,name=should_inject,json=shouldInject,proto3" json:"should_inject,omitempty"`
	ContextText   string                 `protobuf:"bytes,2,opt,name=context_text,json=contextText,proto3" json:"context_text,omitempty"`
	ContextItems  []*ContextItem         `protobuf:"bytes,3,rep,name=context_items,json=contextItems,proto3" json:"context_items,omitempty"`
	Degraded      bool                   `protobuf:"varint,4,opt,name=degraded,proto3" json:"degraded,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCheckResponse) Reset() {
	*x = PreCheckResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCheckResponse) ProtoMessage() {}

func (x *PreCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCheckResponse.ProtoReflect.Descriptor instead.
func (*PreCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{5}
}

func (x *PreCheckResponse) GetShouldInject() bool {
	if x != nil {
		return x.ShouldInject
	}
	return false
}

func (x *PreCheckResponse) GetContextText() string {
	if x != nil {
		return x.ContextText
	}
	return ""
}

func (x *PreCheckResponse) GetContextItems() []*ContextItem {
	if x != nil {
		return x.ContextItems
	}
	return nil
}

func (x *PreCheckResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *PreCheckResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// PostActionTimelineItem carries one middle timeline node from the new text-only contract.
// PostActionTimelineItem 用于承载新纯文本契约中的一条中间时间线节点。
type PostActionTimelineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionTimelineItem) Reset() {
	*x = PostActionTimelineItem{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionTimelineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionTimelineItem) ProtoMessage() {}

func (x *PostActionTimelineItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionTimelineItem.ProtoReflect.Descriptor instead.
func (*PostActionTimelineItem) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{6}
}

func (x *PostActionTimelineItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PostActionTimelineItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PostActionRequest carries the new async post-action contract.
// PostActionRequest 用于承载新的异步 post-action 契约。
type PostActionRequest struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SessionId        string                    `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId           string                    `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId           string                    `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SpaceId          string                    `protobuf:"bytes,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	ProjectId        string                    `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserContent      string                    `protobuf:"bytes,6,opt,name=user_content,json=userContent,proto3" json:"user_content,omitempty"`
	AssistantContent string                    `protobuf:"bytes,7,opt,name=assistant_content,json=assistantContent,proto3" json:"assistant_content,omitempty"`
	Timeline         []*PostActionTimelineItem `protobuf:"bytes,8,rep,name=timeline,proto3" json:"timeline,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PostActionRequest) Reset() {
	*x = PostActionRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionRequest) ProtoMessage() {}

func (x *PostActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionRequest.ProtoReflect.Descriptor instead.
func (*PostActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{7}
}

func (x *PostActionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostActionRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *PostActionRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PostActionRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PostActionRequest) GetUserContent() string {
	if x != nil {
		return x.UserContent
	}
	return ""
}

func (x *PostActionRequest) GetAssistantContent() string {
	if x != nil {
		return x.AssistantContent
	}
	return ""
}

func (x *PostActionRequest) GetTimeline() []*PostActionTimelineItem {
	if x != nil {
		return x.Timeline
	}
	return nil
}

// ToolCall transports legacy tool call metadata for the old post-action contract.
// ToolCall 用于传输旧版 post-action 契约中的工具调用元数据。
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// RawMessage carries one legacy raw snapshot node for the old post-action contract.
// RawMessage 用于承载旧版 post-action 契约中的一条原始快照节点。
type RawMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ContentJson   string                 `protobuf:"bytes,2,opt,name=content_json,json=contentJson,proto3" json:"content_json,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	MetaJson      string                 `protobuf:"bytes,4,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{9}
}

func (x *RawMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RawMessage) GetContentJson() string {
	if x != nil {
		return x.ContentJson
	}
	return ""
}

func (x *RawMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *RawMessage) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

// PostActionOldRequest carries the legacy raw snapshot contract.
// PostActionOldRequest 用于承载旧版原始快照契约。
type PostActionOldRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TeamId              string                 `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SpaceId             string                 `protobuf:"bytes,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	ProjectId           string                 `protobuf:"bytes,5,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RawMessagesSnapshot []*RawMessage          `protobuf:"bytes,6,rep,name=raw_messages_snapshot,json=rawMessagesSnapshot,proto3" json:"raw_messages_snapshot,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PostActionOldRequest) Reset() {
	*x = PostActionOldRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionOldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionOldRequest) ProtoMessage() {}

func (x *PostActionOldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionOldRequest.ProtoReflect.Descriptor instead.
func (*PostActionOldRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{10}
}

func (x *PostActionOldRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostActionOldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PostActionOldRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *PostActionOldRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PostActionOldRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PostActionOldRequest) GetRawMessagesSnapshot() []*RawMessage {
	if x != nil {
		return x.RawMessagesSnapshot
	}
	return nil
}

// PostActionResponse acknowledges whether the request was accepted for processing.
// PostActionResponse 用于确认请求是否已被接受处理。
type PostActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostActionResponse) Reset() {
	*x = PostActionResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostActionResponse) ProtoMessage() {}

func (x *PostActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostActionResponse.ProtoReflect.Descriptor instead.
func (*PostActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{11}
}

func (x *PostActionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PostActionResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// SeedMemoryRequest carries one admin seed-memory request.
// SeedMemoryRequest 用于承载一条管理员 seed-memory 请求。
type SeedMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	MemoryText    string                 `protobuf:"bytes,3,opt,name=memory_text,json=memoryText,proto3" json:"memory_text,omitempty"`
	SpaceId       string                 `protobuf:"bytes,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedMemoryRequest) Reset() {
	*x = SeedMemoryRequest{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedMemoryRequest) ProtoMessage() {}

func (x *SeedMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedMemoryRequest.ProtoReflect.Descriptor instead.
func (*SeedMemoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{12}
}

func (x *SeedMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SeedMemoryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SeedMemoryRequest) GetMemoryText() string {
	if x != nil {
		return x.MemoryText
	}
	return ""
}

func (x *SeedMemoryRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

// SeedMemoryResponse acknowledges the seed request and returns the generated memory id.
// SeedMemoryResponse 用于确认 seed 请求并返回生成的记忆 ID。
type SeedMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	MemoryId      string                 `protobuf:"bytes,2,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeedMemoryResponse) Reset() {
	*x = SeedMemoryResponse{}
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeedMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedMemoryResponse) ProtoMessage() {}

func (x *SeedMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedMemoryResponse.ProtoReflect.Descriptor instead.
func (*SeedMemoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP(), []int{13}
}

func (x *SeedMemoryResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SeedMemoryResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *SeedMemoryResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto protoreflect.FileDescriptor

const file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc = "" +
	"\n" +
	"4internal/adapters/inbound/grpcapi/proto/v1/vmm.proto\x12\x06vmm.v1\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"o\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0faccept_language\x18\x03 \x01(\tR\x0eacceptLanguage\"~\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\xbf\x01\n" +
	"\x0fPreCheckRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\tR\aspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12!\n" +
	"\fuser_content\x18\x06 \x01(\tR\vuserContent\"y\n" +
	"\vContextItem\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"\xcb\x01\n" +
	"\x10PreCheckResponse\x12#\n" +
	"\rshould_inject\x18\x01 \x01(\bR\fshouldInject\x12!\n" +
	"\fcontext_text\x18\x02 \x01(\tR\vcontextText\x128\n" +
	"\rcontext_items\x18\x03 \x03(\v2\x13.vmm.v1.ContextItemR\fcontextItems\x12\x1a\n" +
	"\bdegraded\x18\x04 \x01(\bR\bdegraded\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"F\n" +
	"\x16PostActionTimelineItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xaa\x02\n" +
	"\x11PostActionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\tR\aspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12!\n" +
	"\fuser_content\x18\x06 \x01(\tR\vuserContent\x12+\n" +
	"\x11assistant_content\x18\a \x01(\tR\x10assistantContent\x12:\n" +
	"\btimeline\x18\b \x03(\v2\x1e.vmm.v1.PostActionTimelineItemR\btimeline\".\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x91\x01\n" +
	"\n" +
	"RawMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12!\n" +
	"\fcontent_json\x18\x02 \x01(\tR\vcontentJson\x12/\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x10.vmm.v1.ToolCallR\ttoolCalls\x12\x1b\n" +
	"\tmeta_json\x18\x04 \x01(\tR\bmetaJson\"\xe9\x01\n" +
	"\x14PostActionOldRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\tR\aspaceId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x05 \x01(\tR\tprojectId\x12F\n" +
	"\x15raw_messages_snapshot\x18\x06 \x03(\v2\x12.vmm.v1.RawMessageR\x13rawMessagesSnapshot\"K\n" +
	"\x12PostActionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\x87\x01\n" +
	"\x11SeedMemoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vmemory_text\x18\x03 \x01(\tR\n" +
	"memoryText\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\tR\aspaceId\"h\n" +
	"\x12SeedMemoryResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1b\n" +
	"\tmemory_id\x18\x02 \x01(\tR\bmemoryId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId2\x8f\x03\n" +
	"\n" +
	"VMMService\x12:\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x17.vmm.v1.HealthzResponse\x121\n" +
	"\x04Chat\x12\x13.vmm.v1.ChatRequest\x1a\x14.vmm.v1.ChatResponse\x12=\n" +
	"\bPreCheck\x12\x17.vmm.v1.PreCheckRequest\x1a\x18.vmm.v1.PreCheckResponse\x12C\n" +
	"\n" +
	"PostAction\x12\x19.vmm.v1.PostActionRequest\x1a\x1a.vmm.v1.PostActionResponse\x12I\n" +
	"\rPostActionOld\x12\x1c.vmm.v1.PostActionOldRequest\x1a\x1a.vmm.v1.PostActionResponse\x12C\n" +
	"\n" +
	"SeedMemory\x12\x19.vmm.v1.SeedMemoryRequest\x1a\x1a.vmm.v1.SeedMemoryResponseBLZJgithub.com/openvulcan/vmm/internal/adapters/inbound/grpcapi/proto/v1;vmmv1b\x06proto3"

var (
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescOnce sync.Once
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData []byte
)

func file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescGZIP() []byte {
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescOnce.Do(func() {
		file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc), len(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc)))
	})
	return file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDescData
}

var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes = []any{
	(*HealthzResponse)(nil),        // 0: vmm.v1.HealthzResponse
	(*ChatRequest)(nil),            // 1: vmm.v1.ChatRequest
	(*ChatResponse)(nil),           // 2: vmm.v1.ChatResponse
	(*PreCheckRequest)(nil),        // 3: vmm.v1.PreCheckRequest
	(*ContextItem)(nil),            // 4: vmm.v1.ContextItem
	(*PreCheckResponse)(nil),       // 5: vmm.v1.PreCheckResponse
	(*PostActionTimelineItem)(nil), // 6: vmm.v1.PostActionTimelineItem
	(*PostActionRequest)(nil),      // 7: vmm.v1.PostActionRequest
	(*ToolCall)(nil),               // 8: vmm.v1.ToolCall
	(*RawMessage)(nil),             // 9: vmm.v1.RawMessage
	(*PostActionOldRequest)(nil),   // 10: vmm.v1.PostActionOldRequest
	(*PostActionResponse)(nil),     // 11: vmm.v1.PostActionResponse
	(*SeedMemoryRequest)(nil),      // 12: vmm.v1.SeedMemoryRequest
	(*SeedMemoryResponse)(nil),     // 13: vmm.v1.SeedMemoryResponse
	(*emptypb.Empty)(nil),          // 14: google.protobuf.Empty
}
var file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs = []int32{
	4,  // 0: vmm.v1.PreCheckResponse.context_items:type_name -> vmm.v1.ContextItem
	6,  // 1: vmm.v1.PostActionRequest.timeline:type_name -> vmm.v1.PostActionTimelineItem
	8,  // 2: vmm.v1.RawMessage.tool_calls:type_name -> vmm.v1.ToolCall
	9,  // 3: vmm.v1.PostActionOldRequest.raw_messages_snapshot:type_name -> vmm.v1.RawMessage
	14, // 4: vmm.v1.VMMService.Healthz:input_type -> google.protobuf.Empty
	1,  // 5: vmm.v1.VMMService.Chat:input_type -> vmm.v1.ChatRequest
	3,  // 6: vmm.v1.VMMService.PreCheck:input_type -> vmm.v1.PreCheckRequest
	7,  // 7: vmm.v1.VMMService.PostAction:input_type -> vmm.v1.PostActionRequest
	10, // 8: vmm.v1.VMMService.PostActionOld:input_type -> vmm.v1.PostActionOldRequest
	12, // 9: vmm.v1.VMMService.SeedMemory:input_type -> vmm.v1.SeedMemoryRequest
	0,  // 10: vmm.v1.VMMService.Healthz:output_type -> vmm.v1.HealthzResponse
	2,  // 11: vmm.v1.VMMService.Chat:output_type -> vmm.v1.ChatResponse
	5,  // 12: vmm.v1.VMMService.PreCheck:output_type -> vmm.v1.PreCheckResponse
	11, // 13: vmm.v1.VMMService.PostAction:output_type -> vmm.v1.PostActionResponse
	11, // 14: vmm.v1.VMMService.PostActionOld:output_type -> vmm.v1.PostActionResponse
	13, // 15: vmm.v1.VMMService.SeedMemory:output_type -> vmm.v1.SeedMemoryResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_init() }
func file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_init() {
	if File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc), len(file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes,
		DependencyIndexes: file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs,
		MessageInfos:      file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_msgTypes,
	}.Build()
	File_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto = out.File
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_goTypes = nil
	file_internal_adapters_inbound_grpcapi_proto_v1_vmm_proto_depIdxs = nil
}
