// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: internal/adapters/inbound/grpcapi/proto/v1/vmm.proto

package vmmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMMService_Healthz_FullMethodName                 = "/vmm.v1.VMMService/Healthz"
	VMMService_ListProjects_FullMethodName            = "/vmm.v1.VMMService/ListProjects"
	VMMService_ResolveProject_FullMethodName          = "/vmm.v1.VMMService/ResolveProject"
	VMMService_EnsureProject_FullMethodName           = "/vmm.v1.VMMService/EnsureProject"
	VMMService_DeleteProject_FullMethodName           = "/vmm.v1.VMMService/DeleteProject"
	VMMService_MigrateProject_FullMethodName          = "/vmm.v1.VMMService/MigrateProject"
	VMMService_ResolveUser_FullMethodName             = "/vmm.v1.VMMService/ResolveUser"
	VMMService_ListUsers_FullMethodName               = "/vmm.v1.VMMService/ListUsers"
	VMMService_DeleteUser_FullMethodName              = "/vmm.v1.VMMService/DeleteUser"
	VMMService_GetProfileNodes_FullMethodName         = "/vmm.v1.VMMService/GetProfileNodes"
	VMMService_ApplyProfileInstruction_FullMethodName = "/vmm.v1.VMMService/ApplyProfileInstruction"
	VMMService_PreCheck_FullMethodName                = "/vmm.v1.VMMService/PreCheck"
	VMMService_PostAction_FullMethodName              = "/vmm.v1.VMMService/PostAction"
)

// VMMServiceClient is the client API for VMMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMMService exposes the deterministic hierarchy management surface plus the main PreCheck/PostAction business chain.
// VMMService 用于暴露确定性层级管理接口，以及主业务链路 PreCheck/PostAction。
type VMMServiceClient interface {
	// Healthz reports whether the local gateway process is alive.
	// Healthz 用于报告本地网关进程是否存活。
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
	// ListProjects returns all Team/Space/Project paths in deterministic display order.
	// ListProjects 用于按稳定展示顺序返回全部 Team/Space/Project 路径。
	ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	// ResolveProject resolves one project by numeric id or canonical Team/Space/Project path.
	// ResolveProject 用于按数字 ID 或标准 Team/Space/Project 路径解析单个项目。
	ResolveProject(ctx context.Context, in *ResolveProjectRequest, opts ...grpc.CallOption) (*ResolveProjectResponse, error)
	// EnsureProject resolves or creates one Team/Space/Project path according to the confirm-create contract.
	// EnsureProject 用于按 confirm_create 规则解析或创建 Team/Space/Project 路径。
	EnsureProject(ctx context.Context, in *EnsureProjectRequest, opts ...grpc.CallOption) (*EnsureProjectResponse, error)
	// DeleteProject deletes one project path and its SQL/vector data after explicit confirmation.
	// DeleteProject 用于在显式确认后删除单个项目路径及其 SQL/向量数据。
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error)
	// MigrateProject moves all SQL/vector data from one source project path onto another target project path.
	// MigrateProject 用于把某个源项目路径下的全部 SQL/向量数据迁移到目标项目路径。
	MigrateProject(ctx context.Context, in *MigrateProjectRequest, opts ...grpc.CallOption) (*MigrateProjectResponse, error)
	// ResolveUser resolves one user by numeric id or name, and can optionally create it when confirm_create is true.
	// ResolveUser 用于按数字 ID 或名称解析用户，并在 confirm_create 为真时按需创建用户。
	ResolveUser(ctx context.Context, in *ResolveUserRequest, opts ...grpc.CallOption) (*ResolveUserResponse, error)
	// ListUsers returns the durable user list.
	// ListUsers 用于返回长期用户列表。
	ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// DeleteUser removes one user and all SQL/vector data after the caller presents the generated confirmation code.
	// DeleteUser 用于在调用方提交生成的确认码后，删除单个用户及其全部 SQL/向量数据。
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// GetProfileNodes returns only active atomic profile nodes for one requested scope target.
	// GetProfileNodes 用于返回单个目标范围下当前 active 的原子化画像节点。
	GetProfileNodes(ctx context.Context, in *GetProfileNodesRequest, opts ...grpc.CallOption) (*GetProfileNodesResponse, error)
	// ApplyProfileInstruction accepts one explicit manual profile instruction for one target and persists the reviewed node changes.
	// ApplyProfileInstruction 用于接收单个目标上的显式手工画像指令，并持久化评审后的节点变更。
	ApplyProfileInstruction(ctx context.Context, in *ApplyProfileInstructionRequest, opts ...grpc.CallOption) (*ApplyProfileInstructionResponse, error)
	// PreCheck validates project_id/user_id through the interceptor and currently returns a deterministic no-injection response.
	// PreCheck 用于通过拦截器校验 project_id/user_id，并在当前阶段返回稳定的“不需要记忆”响应。
	PreCheck(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error)
	// PostAction validates project_id/user_id through the interceptor, logs the payload, and persists the cleaned message sequence asynchronously.
	// PostAction 用于通过拦截器校验 project_id/user_id、打印载荷日志，并异步持久化清洗后的消息序列。
	PostAction(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostActionResponse, error)
}

type vMMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMMServiceClient(cc grpc.ClientConnInterface) VMMServiceClient {
	return &vMMServiceClient{cc}
}

func (c *vMMServiceClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, VMMService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) ListProjects(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, VMMService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) ResolveProject(ctx context.Context, in *ResolveProjectRequest, opts ...grpc.CallOption) (*ResolveProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveProjectResponse)
	err := c.cc.Invoke(ctx, VMMService_ResolveProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) EnsureProject(ctx context.Context, in *EnsureProjectRequest, opts ...grpc.CallOption) (*EnsureProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureProjectResponse)
	err := c.cc.Invoke(ctx, VMMService_EnsureProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*DeleteProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProjectResponse)
	err := c.cc.Invoke(ctx, VMMService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) MigrateProject(ctx context.Context, in *MigrateProjectRequest, opts ...grpc.CallOption) (*MigrateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateProjectResponse)
	err := c.cc.Invoke(ctx, VMMService_MigrateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) ResolveUser(ctx context.Context, in *ResolveUserRequest, opts ...grpc.CallOption) (*ResolveUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveUserResponse)
	err := c.cc.Invoke(ctx, VMMService_ResolveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) ListUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, VMMService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, VMMService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) GetProfileNodes(ctx context.Context, in *GetProfileNodesRequest, opts ...grpc.CallOption) (*GetProfileNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileNodesResponse)
	err := c.cc.Invoke(ctx, VMMService_GetProfileNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) ApplyProfileInstruction(ctx context.Context, in *ApplyProfileInstructionRequest, opts ...grpc.CallOption) (*ApplyProfileInstructionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProfileInstructionResponse)
	err := c.cc.Invoke(ctx, VMMService_ApplyProfileInstruction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) PreCheck(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckResponse)
	err := c.cc.Invoke(ctx, VMMService_PreCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) PostAction(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostActionResponse)
	err := c.cc.Invoke(ctx, VMMService_PostAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMMServiceServer is the server API for VMMService service.
// All implementations must embed UnimplementedVMMServiceServer
// for forward compatibility.
//
// VMMService exposes the deterministic hierarchy management surface plus the main PreCheck/PostAction business chain.
// VMMService 用于暴露确定性层级管理接口，以及主业务链路 PreCheck/PostAction。
type VMMServiceServer interface {
	// Healthz reports whether the local gateway process is alive.
	// Healthz 用于报告本地网关进程是否存活。
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	// ListProjects returns all Team/Space/Project paths in deterministic display order.
	// ListProjects 用于按稳定展示顺序返回全部 Team/Space/Project 路径。
	ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error)
	// ResolveProject resolves one project by numeric id or canonical Team/Space/Project path.
	// ResolveProject 用于按数字 ID 或标准 Team/Space/Project 路径解析单个项目。
	ResolveProject(context.Context, *ResolveProjectRequest) (*ResolveProjectResponse, error)
	// EnsureProject resolves or creates one Team/Space/Project path according to the confirm-create contract.
	// EnsureProject 用于按 confirm_create 规则解析或创建 Team/Space/Project 路径。
	EnsureProject(context.Context, *EnsureProjectRequest) (*EnsureProjectResponse, error)
	// DeleteProject deletes one project path and its SQL/vector data after explicit confirmation.
	// DeleteProject 用于在显式确认后删除单个项目路径及其 SQL/向量数据。
	DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error)
	// MigrateProject moves all SQL/vector data from one source project path onto another target project path.
	// MigrateProject 用于把某个源项目路径下的全部 SQL/向量数据迁移到目标项目路径。
	MigrateProject(context.Context, *MigrateProjectRequest) (*MigrateProjectResponse, error)
	// ResolveUser resolves one user by numeric id or name, and can optionally create it when confirm_create is true.
	// ResolveUser 用于按数字 ID 或名称解析用户，并在 confirm_create 为真时按需创建用户。
	ResolveUser(context.Context, *ResolveUserRequest) (*ResolveUserResponse, error)
	// ListUsers returns the durable user list.
	// ListUsers 用于返回长期用户列表。
	ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error)
	// DeleteUser removes one user and all SQL/vector data after the caller presents the generated confirmation code.
	// DeleteUser 用于在调用方提交生成的确认码后，删除单个用户及其全部 SQL/向量数据。
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// GetProfileNodes returns only active atomic profile nodes for one requested scope target.
	// GetProfileNodes 用于返回单个目标范围下当前 active 的原子化画像节点。
	GetProfileNodes(context.Context, *GetProfileNodesRequest) (*GetProfileNodesResponse, error)
	// ApplyProfileInstruction accepts one explicit manual profile instruction for one target and persists the reviewed node changes.
	// ApplyProfileInstruction 用于接收单个目标上的显式手工画像指令，并持久化评审后的节点变更。
	ApplyProfileInstruction(context.Context, *ApplyProfileInstructionRequest) (*ApplyProfileInstructionResponse, error)
	// PreCheck validates project_id/user_id through the interceptor and currently returns a deterministic no-injection response.
	// PreCheck 用于通过拦截器校验 project_id/user_id，并在当前阶段返回稳定的“不需要记忆”响应。
	PreCheck(context.Context, *PreCheckRequest) (*PreCheckResponse, error)
	// PostAction validates project_id/user_id through the interceptor, logs the payload, and persists the cleaned message sequence asynchronously.
	// PostAction 用于通过拦截器校验 project_id/user_id、打印载荷日志，并异步持久化清洗后的消息序列。
	PostAction(context.Context, *PostActionRequest) (*PostActionResponse, error)
	mustEmbedUnimplementedVMMServiceServer()
}

// UnimplementedVMMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMMServiceServer struct{}

func (UnimplementedVMMServiceServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedVMMServiceServer) ListProjects(context.Context, *emptypb.Empty) (*ListProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedVMMServiceServer) ResolveProject(context.Context, *ResolveProjectRequest) (*ResolveProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveProject not implemented")
}
func (UnimplementedVMMServiceServer) EnsureProject(context.Context, *EnsureProjectRequest) (*EnsureProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureProject not implemented")
}
func (UnimplementedVMMServiceServer) DeleteProject(context.Context, *DeleteProjectRequest) (*DeleteProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedVMMServiceServer) MigrateProject(context.Context, *MigrateProjectRequest) (*MigrateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateProject not implemented")
}
func (UnimplementedVMMServiceServer) ResolveUser(context.Context, *ResolveUserRequest) (*ResolveUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveUser not implemented")
}
func (UnimplementedVMMServiceServer) ListUsers(context.Context, *emptypb.Empty) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedVMMServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedVMMServiceServer) GetProfileNodes(context.Context, *GetProfileNodesRequest) (*GetProfileNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileNodes not implemented")
}
func (UnimplementedVMMServiceServer) ApplyProfileInstruction(context.Context, *ApplyProfileInstructionRequest) (*ApplyProfileInstructionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyProfileInstruction not implemented")
}
func (UnimplementedVMMServiceServer) PreCheck(context.Context, *PreCheckRequest) (*PreCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreCheck not implemented")
}
func (UnimplementedVMMServiceServer) PostAction(context.Context, *PostActionRequest) (*PostActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAction not implemented")
}
func (UnimplementedVMMServiceServer) mustEmbedUnimplementedVMMServiceServer() {}
func (UnimplementedVMMServiceServer) testEmbeddedByValue()                    {}

// UnsafeVMMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMMServiceServer will
// result in compilation errors.
type UnsafeVMMServiceServer interface {
	mustEmbedUnimplementedVMMServiceServer()
}

func RegisterVMMServiceServer(s grpc.ServiceRegistrar, srv VMMServiceServer) {
	// If the following call pancis, it indicates UnimplementedVMMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMMService_ServiceDesc, srv)
}

func _VMMService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).ListProjects(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_ResolveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).ResolveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_ResolveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).ResolveProject(ctx, req.(*ResolveProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_EnsureProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).EnsureProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_EnsureProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).EnsureProject(ctx, req.(*EnsureProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_MigrateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).MigrateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_MigrateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).MigrateProject(ctx, req.(*MigrateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_ResolveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).ResolveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_ResolveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).ResolveUser(ctx, req.(*ResolveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).ListUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_GetProfileNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).GetProfileNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_GetProfileNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).GetProfileNodes(ctx, req.(*GetProfileNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_ApplyProfileInstruction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProfileInstructionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).ApplyProfileInstruction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_ApplyProfileInstruction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).ApplyProfileInstruction(ctx, req.(*ApplyProfileInstructionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_PreCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).PreCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_PreCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).PreCheck(ctx, req.(*PreCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_PostAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).PostAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_PostAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).PostAction(ctx, req.(*PostActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMMService_ServiceDesc is the grpc.ServiceDesc for VMMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmm.v1.VMMService",
	HandlerType: (*VMMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _VMMService_Healthz_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _VMMService_ListProjects_Handler,
		},
		{
			MethodName: "ResolveProject",
			Handler:    _VMMService_ResolveProject_Handler,
		},
		{
			MethodName: "EnsureProject",
			Handler:    _VMMService_EnsureProject_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _VMMService_DeleteProject_Handler,
		},
		{
			MethodName: "MigrateProject",
			Handler:    _VMMService_MigrateProject_Handler,
		},
		{
			MethodName: "ResolveUser",
			Handler:    _VMMService_ResolveUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _VMMService_ListUsers_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _VMMService_DeleteUser_Handler,
		},
		{
			MethodName: "GetProfileNodes",
			Handler:    _VMMService_GetProfileNodes_Handler,
		},
		{
			MethodName: "ApplyProfileInstruction",
			Handler:    _VMMService_ApplyProfileInstruction_Handler,
		},
		{
			MethodName: "PreCheck",
			Handler:    _VMMService_PreCheck_Handler,
		},
		{
			MethodName: "PostAction",
			Handler:    _VMMService_PostAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/adapters/inbound/grpcapi/proto/v1/vmm.proto",
}
