// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: internal/adapters/inbound/grpcapi/proto/v1/vmm.proto

package vmmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VMMService_Healthz_FullMethodName       = "/vmm.v1.VMMService/Healthz"
	VMMService_Chat_FullMethodName          = "/vmm.v1.VMMService/Chat"
	VMMService_PreCheck_FullMethodName      = "/vmm.v1.VMMService/PreCheck"
	VMMService_PostAction_FullMethodName    = "/vmm.v1.VMMService/PostAction"
	VMMService_PostActionOld_FullMethodName = "/vmm.v1.VMMService/PostActionOld"
	VMMService_SeedMemory_FullMethodName    = "/vmm.v1.VMMService/SeedMemory"
)

// VMMServiceClient is the client API for VMMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VMMService exposes the local gateway workflows over gRPC.
// VMMService 用于通过 gRPC 暴露本地网关工作流。
type VMMServiceClient interface {
	// Healthz reports whether the local gateway process is alive.
	// Healthz 用于报告本地网关进程是否存活。
	Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error)
	// Chat scrubs one inbound message and archives the sanitized text.
	// Chat 用于脱敏一条入站消息并归档清洗后的文本。
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error)
	// PreCheck decides whether the current user text needs memory injection.
	// PreCheck 用于判断当前用户文本是否需要记忆注入。
	PreCheck(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error)
	// PostAction accepts the new text-only contract and continues processing asynchronously.
	// PostAction 用于接收新的纯文本契约，并在后台继续异步处理。
	PostAction(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostActionResponse, error)
	// PostActionOld preserves the legacy raw snapshot contract during migration.
	// PostActionOld 用于在迁移期间保留旧版原始快照契约。
	PostActionOld(ctx context.Context, in *PostActionOldRequest, opts ...grpc.CallOption) (*PostActionResponse, error)
	// SeedMemory preloads one memory entry into the vector backend for local testing.
	// SeedMemory 用于为本地测试向向量后端预热一条记忆。
	SeedMemory(ctx context.Context, in *SeedMemoryRequest, opts ...grpc.CallOption) (*SeedMemoryResponse, error)
}

type vMMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMMServiceClient(cc grpc.ClientConnInterface) VMMServiceClient {
	return &vMMServiceClient{cc}
}

func (c *vMMServiceClient) Healthz(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, VMMService_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (*ChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatResponse)
	err := c.cc.Invoke(ctx, VMMService_Chat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) PreCheck(ctx context.Context, in *PreCheckRequest, opts ...grpc.CallOption) (*PreCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreCheckResponse)
	err := c.cc.Invoke(ctx, VMMService_PreCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) PostAction(ctx context.Context, in *PostActionRequest, opts ...grpc.CallOption) (*PostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostActionResponse)
	err := c.cc.Invoke(ctx, VMMService_PostAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) PostActionOld(ctx context.Context, in *PostActionOldRequest, opts ...grpc.CallOption) (*PostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostActionResponse)
	err := c.cc.Invoke(ctx, VMMService_PostActionOld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMMServiceClient) SeedMemory(ctx context.Context, in *SeedMemoryRequest, opts ...grpc.CallOption) (*SeedMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeedMemoryResponse)
	err := c.cc.Invoke(ctx, VMMService_SeedMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMMServiceServer is the server API for VMMService service.
// All implementations must embed UnimplementedVMMServiceServer
// for forward compatibility.
//
// VMMService exposes the local gateway workflows over gRPC.
// VMMService 用于通过 gRPC 暴露本地网关工作流。
type VMMServiceServer interface {
	// Healthz reports whether the local gateway process is alive.
	// Healthz 用于报告本地网关进程是否存活。
	Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error)
	// Chat scrubs one inbound message and archives the sanitized text.
	// Chat 用于脱敏一条入站消息并归档清洗后的文本。
	Chat(context.Context, *ChatRequest) (*ChatResponse, error)
	// PreCheck decides whether the current user text needs memory injection.
	// PreCheck 用于判断当前用户文本是否需要记忆注入。
	PreCheck(context.Context, *PreCheckRequest) (*PreCheckResponse, error)
	// PostAction accepts the new text-only contract and continues processing asynchronously.
	// PostAction 用于接收新的纯文本契约，并在后台继续异步处理。
	PostAction(context.Context, *PostActionRequest) (*PostActionResponse, error)
	// PostActionOld preserves the legacy raw snapshot contract during migration.
	// PostActionOld 用于在迁移期间保留旧版原始快照契约。
	PostActionOld(context.Context, *PostActionOldRequest) (*PostActionResponse, error)
	// SeedMemory preloads one memory entry into the vector backend for local testing.
	// SeedMemory 用于为本地测试向向量后端预热一条记忆。
	SeedMemory(context.Context, *SeedMemoryRequest) (*SeedMemoryResponse, error)
	mustEmbedUnimplementedVMMServiceServer()
}

// UnimplementedVMMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVMMServiceServer struct{}

func (UnimplementedVMMServiceServer) Healthz(context.Context, *emptypb.Empty) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedVMMServiceServer) Chat(context.Context, *ChatRequest) (*ChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedVMMServiceServer) PreCheck(context.Context, *PreCheckRequest) (*PreCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreCheck not implemented")
}
func (UnimplementedVMMServiceServer) PostAction(context.Context, *PostActionRequest) (*PostActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAction not implemented")
}
func (UnimplementedVMMServiceServer) PostActionOld(context.Context, *PostActionOldRequest) (*PostActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostActionOld not implemented")
}
func (UnimplementedVMMServiceServer) SeedMemory(context.Context, *SeedMemoryRequest) (*SeedMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeedMemory not implemented")
}
func (UnimplementedVMMServiceServer) mustEmbedUnimplementedVMMServiceServer() {}
func (UnimplementedVMMServiceServer) testEmbeddedByValue()                    {}

// UnsafeVMMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMMServiceServer will
// result in compilation errors.
type UnsafeVMMServiceServer interface {
	mustEmbedUnimplementedVMMServiceServer()
}

func RegisterVMMServiceServer(s grpc.ServiceRegistrar, srv VMMServiceServer) {
	// If the following call pancis, it indicates UnimplementedVMMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VMMService_ServiceDesc, srv)
}

func _VMMService_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).Healthz(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_Chat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).Chat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_Chat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).Chat(ctx, req.(*ChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_PreCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).PreCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_PreCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).PreCheck(ctx, req.(*PreCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_PostAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).PostAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_PostAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).PostAction(ctx, req.(*PostActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_PostActionOld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostActionOldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).PostActionOld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_PostActionOld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).PostActionOld(ctx, req.(*PostActionOldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMMService_SeedMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMMServiceServer).SeedMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VMMService_SeedMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMMServiceServer).SeedMemory(ctx, req.(*SeedMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMMService_ServiceDesc is the grpc.ServiceDesc for VMMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmm.v1.VMMService",
	HandlerType: (*VMMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _VMMService_Healthz_Handler,
		},
		{
			MethodName: "Chat",
			Handler:    _VMMService_Chat_Handler,
		},
		{
			MethodName: "PreCheck",
			Handler:    _VMMService_PreCheck_Handler,
		},
		{
			MethodName: "PostAction",
			Handler:    _VMMService_PostAction_Handler,
		},
		{
			MethodName: "PostActionOld",
			Handler:    _VMMService_PostActionOld_Handler,
		},
		{
			MethodName: "SeedMemory",
			Handler:    _VMMService_SeedMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/adapters/inbound/grpcapi/proto/v1/vmm.proto",
}
