// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: internal/adapters/outbound/vldb_sqlite/proto/v1/sqlite.proto

package sqlitev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SqliteService_ExecuteScript_FullMethodName = "/vldb.sqlite.v1.SqliteService/ExecuteScript"
	SqliteService_ExecuteBatch_FullMethodName  = "/vldb.sqlite.v1.SqliteService/ExecuteBatch"
	SqliteService_QueryJson_FullMethodName     = "/vldb.sqlite.v1.SqliteService/QueryJson"
	SqliteService_QueryStream_FullMethodName   = "/vldb.sqlite.v1.SqliteService/QueryStream"
)

// SqliteServiceClient is the client API for SqliteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SqliteServiceClient interface {
	ExecuteScript(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error)
	QueryJson(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryJsonResponse, error)
	QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
}

type sqliteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSqliteServiceClient(cc grpc.ClientConnInterface) SqliteServiceClient {
	return &sqliteServiceClient{cc}
}

func (c *sqliteServiceClient) ExecuteScript(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, SqliteService_ExecuteScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqliteServiceClient) ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBatchResponse)
	err := c.cc.Invoke(ctx, SqliteService_ExecuteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqliteServiceClient) QueryJson(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryJsonResponse)
	err := c.cc.Invoke(ctx, SqliteService_QueryJson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqliteServiceClient) QueryStream(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SqliteService_ServiceDesc.Streams[0], SqliteService_QueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqliteService_QueryStreamClient = grpc.ServerStreamingClient[QueryResponse]

// SqliteServiceServer is the server API for SqliteService service.
// All implementations must embed UnimplementedSqliteServiceServer
// for forward compatibility.
type SqliteServiceServer interface {
	ExecuteScript(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error)
	QueryJson(context.Context, *QueryRequest) (*QueryJsonResponse, error)
	QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error
	mustEmbedUnimplementedSqliteServiceServer()
}

// UnimplementedSqliteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqliteServiceServer struct{}

func (UnimplementedSqliteServiceServer) ExecuteScript(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (UnimplementedSqliteServiceServer) ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedSqliteServiceServer) QueryJson(context.Context, *QueryRequest) (*QueryJsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryJson not implemented")
}
func (UnimplementedSqliteServiceServer) QueryStream(*QueryRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method QueryStream not implemented")
}
func (UnimplementedSqliteServiceServer) mustEmbedUnimplementedSqliteServiceServer() {}
func (UnimplementedSqliteServiceServer) testEmbeddedByValue()                       {}

// UnsafeSqliteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqliteServiceServer will
// result in compilation errors.
type UnsafeSqliteServiceServer interface {
	mustEmbedUnimplementedSqliteServiceServer()
}

func RegisterSqliteServiceServer(s grpc.ServiceRegistrar, srv SqliteServiceServer) {
	// If the following call pancis, it indicates UnimplementedSqliteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqliteService_ServiceDesc, srv)
}

func _SqliteService_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqliteServiceServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqliteService_ExecuteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqliteServiceServer).ExecuteScript(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqliteService_ExecuteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqliteServiceServer).ExecuteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqliteService_ExecuteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqliteServiceServer).ExecuteBatch(ctx, req.(*ExecuteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqliteService_QueryJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqliteServiceServer).QueryJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqliteService_QueryJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqliteServiceServer).QueryJson(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqliteService_QueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SqliteServiceServer).QueryStream(m, &grpc.GenericServerStream[QueryRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SqliteService_QueryStreamServer = grpc.ServerStreamingServer[QueryResponse]

// SqliteService_ServiceDesc is the grpc.ServiceDesc for SqliteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqliteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vldb.sqlite.v1.SqliteService",
	HandlerType: (*SqliteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteScript",
			Handler:    _SqliteService_ExecuteScript_Handler,
		},
		{
			MethodName: "ExecuteBatch",
			Handler:    _SqliteService_ExecuteBatch_Handler,
		},
		{
			MethodName: "QueryJson",
			Handler:    _SqliteService_QueryJson_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryStream",
			Handler:       _SqliteService_QueryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/adapters/outbound/vldb_sqlite/proto/v1/sqlite.proto",
}
