// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/adapters/outbound/vldb_sqlite/proto/v1/sqlite.proto

package sqlitev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{0}
}

type SqliteValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SqliteValue_Int64Value
	//	*SqliteValue_Float64Value
	//	*SqliteValue_StringValue
	//	*SqliteValue_BytesValue
	//	*SqliteValue_BoolValue
	//	*SqliteValue_NullValue
	Kind          isSqliteValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqliteValue) Reset() {
	*x = SqliteValue{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqliteValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqliteValue) ProtoMessage() {}

func (x *SqliteValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqliteValue.ProtoReflect.Descriptor instead.
func (*SqliteValue) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{1}
}

func (x *SqliteValue) GetKind() isSqliteValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SqliteValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *SqliteValue) GetFloat64Value() float64 {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_Float64Value); ok {
			return x.Float64Value
		}
	}
	return 0
}

func (x *SqliteValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *SqliteValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *SqliteValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *SqliteValue) GetNullValue() *NullValue {
	if x != nil {
		if x, ok := x.Kind.(*SqliteValue_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

type isSqliteValue_Kind interface {
	isSqliteValue_Kind()
}

type SqliteValue_Int64Value struct {
	Int64Value int64 `protobuf:"zigzag64,1,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type SqliteValue_Float64Value struct {
	Float64Value float64 `protobuf:"fixed64,2,opt,name=float64_value,json=float64Value,proto3,oneof"`
}

type SqliteValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type SqliteValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,4,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type SqliteValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type SqliteValue_NullValue struct {
	NullValue *NullValue `protobuf:"bytes,6,opt,name=null_value,json=nullValue,proto3,oneof"`
}

func (*SqliteValue_Int64Value) isSqliteValue_Kind() {}

func (*SqliteValue_Float64Value) isSqliteValue_Kind() {}

func (*SqliteValue_StringValue) isSqliteValue_Kind() {}

func (*SqliteValue_BytesValue) isSqliteValue_Kind() {}

func (*SqliteValue_BoolValue) isSqliteValue_Kind() {}

func (*SqliteValue_NullValue) isSqliteValue_Kind() {}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	Params        []*SqliteValue         `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []*SqliteValue {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RowsChanged     int64                  `protobuf:"varint,3,opt,name=rows_changed,json=rowsChanged,proto3" json:"rows_changed,omitempty"`
	LastInsertRowid int64                  `protobuf:"varint,4,opt,name=last_insert_rowid,json=lastInsertRowid,proto3" json:"last_insert_rowid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteResponse) GetRowsChanged() int64 {
	if x != nil {
		return x.RowsChanged
	}
	return 0
}

func (x *ExecuteResponse) GetLastInsertRowid() int64 {
	if x != nil {
		return x.LastInsertRowid
	}
	return 0
}

type ExecuteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Items         []*ExecuteBatchItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchRequest) Reset() {
	*x = ExecuteBatchRequest{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchRequest) ProtoMessage() {}

func (x *ExecuteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteBatchRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteBatchRequest) GetItems() []*ExecuteBatchItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ExecuteBatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*SqliteValue         `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchItem) Reset() {
	*x = ExecuteBatchItem{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchItem) ProtoMessage() {}

func (x *ExecuteBatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchItem.ProtoReflect.Descriptor instead.
func (*ExecuteBatchItem) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteBatchItem) GetParams() []*SqliteValue {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteBatchResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RowsChanged        int64                  `protobuf:"varint,3,opt,name=rows_changed,json=rowsChanged,proto3" json:"rows_changed,omitempty"`
	LastInsertRowid    int64                  `protobuf:"varint,4,opt,name=last_insert_rowid,json=lastInsertRowid,proto3" json:"last_insert_rowid,omitempty"`
	StatementsExecuted int64                  `protobuf:"varint,5,opt,name=statements_executed,json=statementsExecuted,proto3" json:"statements_executed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteBatchResponse) Reset() {
	*x = ExecuteBatchResponse{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchResponse) ProtoMessage() {}

func (x *ExecuteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteBatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteBatchResponse) GetRowsChanged() int64 {
	if x != nil {
		return x.RowsChanged
	}
	return 0
}

func (x *ExecuteBatchResponse) GetLastInsertRowid() int64 {
	if x != nil {
		return x.LastInsertRowid
	}
	return 0
}

func (x *ExecuteBatchResponse) GetStatementsExecuted() int64 {
	if x != nil {
		return x.StatementsExecuted
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	Params        []*SqliteValue         `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *QueryRequest) GetParams() []*SqliteValue {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArrowIpcChunk []byte                 `protobuf:"bytes,1,opt,name=arrow_ipc_chunk,json=arrowIpcChunk,proto3" json:"arrow_ipc_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetArrowIpcChunk() []byte {
	if x != nil {
		return x.ArrowIpcChunk
	}
	return nil
}

type QueryJsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryJsonResponse) Reset() {
	*x = QueryJsonResponse{}
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryJsonResponse) ProtoMessage() {}

func (x *QueryJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryJsonResponse.ProtoReflect.Descriptor instead.
func (*QueryJsonResponse) Descriptor() ([]byte, []int) {
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP(), []int{9}
}

func (x *QueryJsonResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto protoreflect.FileDescriptor

const file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDesc = "" +
	"\n" +
	"<internal/adapters/outbound/vldb_sqlite/proto/v1/sqlite.proto\x12\x0evldb.sqlite.v1\"\v\n" +
	"\tNullValue\"\x84\x02\n" +
	"\vSqliteValue\x12!\n" +
	"\vint64_value\x18\x01 \x01(\x12H\x00R\n" +
	"int64Value\x12%\n" +
	"\rfloat64_value\x18\x02 \x01(\x01H\x00R\ffloat64Value\x12#\n" +
	"\fstring_value\x18\x03 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x04 \x01(\fH\x00R\n" +
	"bytesValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12:\n" +
	"\n" +
	"null_value\x18\x06 \x01(\v2\x19.vldb.sqlite.v1.NullValueH\x00R\tnullValueB\x06\n" +
	"\x04kind\"x\n" +
	"\x0eExecuteRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\x123\n" +
	"\x06params\x18\x03 \x03(\v2\x1b.vldb.sqlite.v1.SqliteValueR\x06params\"\x94\x01\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\frows_changed\x18\x03 \x01(\x03R\vrowsChanged\x12*\n" +
	"\x11last_insert_rowid\x18\x04 \x01(\x03R\x0flastInsertRowid\"_\n" +
	"\x13ExecuteBatchRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .vldb.sqlite.v1.ExecuteBatchItemR\x05items\"G\n" +
	"\x10ExecuteBatchItem\x123\n" +
	"\x06params\x18\x01 \x03(\v2\x1b.vldb.sqlite.v1.SqliteValueR\x06params\"\xca\x01\n" +
	"\x14ExecuteBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\frows_changed\x18\x03 \x01(\x03R\vrowsChanged\x12*\n" +
	"\x11last_insert_rowid\x18\x04 \x01(\x03R\x0flastInsertRowid\x12/\n" +
	"\x13statements_executed\x18\x05 \x01(\x03R\x12statementsExecuted\"v\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\x123\n" +
	"\x06params\x18\x03 \x03(\v2\x1b.vldb.sqlite.v1.SqliteValueR\x06params\"7\n" +
	"\rQueryResponse\x12&\n" +
	"\x0farrow_ipc_chunk\x18\x01 \x01(\fR\rarrowIpcChunk\"0\n" +
	"\x11QueryJsonResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData2\xd8\x02\n" +
	"\rSqliteService\x12P\n" +
	"\rExecuteScript\x12\x1e.vldb.sqlite.v1.ExecuteRequest\x1a\x1f.vldb.sqlite.v1.ExecuteResponse\x12Y\n" +
	"\fExecuteBatch\x12#.vldb.sqlite.v1.ExecuteBatchRequest\x1a$.vldb.sqlite.v1.ExecuteBatchResponse\x12L\n" +
	"\tQueryJson\x12\x1c.vldb.sqlite.v1.QueryRequest\x1a!.vldb.sqlite.v1.QueryJsonResponse\x12L\n" +
	"\vQueryStream\x12\x1c.vldb.sqlite.v1.QueryRequest\x1a\x1d.vldb.sqlite.v1.QueryResponse0\x01BTZRgithub.com/openvulcan/vmm/internal/adapters/outbound/vldb_sqlite/proto/v1;sqlitev1b\x06proto3"

var (
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescOnce sync.Once
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescData []byte
)

func file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescGZIP() []byte {
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescOnce.Do(func() {
		file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDesc), len(file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDesc)))
	})
	return file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDescData
}

var file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_goTypes = []any{
	(*NullValue)(nil),            // 0: vldb.sqlite.v1.NullValue
	(*SqliteValue)(nil),          // 1: vldb.sqlite.v1.SqliteValue
	(*ExecuteRequest)(nil),       // 2: vldb.sqlite.v1.ExecuteRequest
	(*ExecuteResponse)(nil),      // 3: vldb.sqlite.v1.ExecuteResponse
	(*ExecuteBatchRequest)(nil),  // 4: vldb.sqlite.v1.ExecuteBatchRequest
	(*ExecuteBatchItem)(nil),     // 5: vldb.sqlite.v1.ExecuteBatchItem
	(*ExecuteBatchResponse)(nil), // 6: vldb.sqlite.v1.ExecuteBatchResponse
	(*QueryRequest)(nil),         // 7: vldb.sqlite.v1.QueryRequest
	(*QueryResponse)(nil),        // 8: vldb.sqlite.v1.QueryResponse
	(*QueryJsonResponse)(nil),    // 9: vldb.sqlite.v1.QueryJsonResponse
}
var file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_depIdxs = []int32{
	0, // 0: vldb.sqlite.v1.SqliteValue.null_value:type_name -> vldb.sqlite.v1.NullValue
	1, // 1: vldb.sqlite.v1.ExecuteRequest.params:type_name -> vldb.sqlite.v1.SqliteValue
	5, // 2: vldb.sqlite.v1.ExecuteBatchRequest.items:type_name -> vldb.sqlite.v1.ExecuteBatchItem
	1, // 3: vldb.sqlite.v1.ExecuteBatchItem.params:type_name -> vldb.sqlite.v1.SqliteValue
	1, // 4: vldb.sqlite.v1.QueryRequest.params:type_name -> vldb.sqlite.v1.SqliteValue
	2, // 5: vldb.sqlite.v1.SqliteService.ExecuteScript:input_type -> vldb.sqlite.v1.ExecuteRequest
	4, // 6: vldb.sqlite.v1.SqliteService.ExecuteBatch:input_type -> vldb.sqlite.v1.ExecuteBatchRequest
	7, // 7: vldb.sqlite.v1.SqliteService.QueryJson:input_type -> vldb.sqlite.v1.QueryRequest
	7, // 8: vldb.sqlite.v1.SqliteService.QueryStream:input_type -> vldb.sqlite.v1.QueryRequest
	3, // 9: vldb.sqlite.v1.SqliteService.ExecuteScript:output_type -> vldb.sqlite.v1.ExecuteResponse
	6, // 10: vldb.sqlite.v1.SqliteService.ExecuteBatch:output_type -> vldb.sqlite.v1.ExecuteBatchResponse
	9, // 11: vldb.sqlite.v1.SqliteService.QueryJson:output_type -> vldb.sqlite.v1.QueryJsonResponse
	8, // 12: vldb.sqlite.v1.SqliteService.QueryStream:output_type -> vldb.sqlite.v1.QueryResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_init() }
func file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_init() {
	if File_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto != nil {
		return
	}
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes[1].OneofWrappers = []any{
		(*SqliteValue_Int64Value)(nil),
		(*SqliteValue_Float64Value)(nil),
		(*SqliteValue_StringValue)(nil),
		(*SqliteValue_BytesValue)(nil),
		(*SqliteValue_BoolValue)(nil),
		(*SqliteValue_NullValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDesc), len(file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_goTypes,
		DependencyIndexes: file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_depIdxs,
		MessageInfos:      file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_msgTypes,
	}.Build()
	File_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto = out.File
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_goTypes = nil
	file_internal_adapters_outbound_vldb_sqlite_proto_v1_sqlite_proto_depIdxs = nil
}
